### ISSUE TITLE
Appends _currency to non-money ExpressionFields

### ISSUE THREAD

**Issue by AlexRiina** [django-money/django-money#101]
It seems like `_expand_money_params` [processes all ExpressionNodes (e.g. Q and F) as if they are MoneyFields which leads to querying for `$field_currency`](https://github.com/jakewins/django-money/blob/master/djmoney/models/managers.py#L36). I had some trouble getting all of the tests to pass (and your travis-ci widget points to the wrong project), but the below should evidence the error.

```python
diff --git a/djmoney/tests/model_tests.py b/djmoney/tests/model_tests.py
index 974be95..d062853 100644
--- a/djmoney/tests/model_tests.py
+++ b/djmoney/tests/model_tests.py
@@ -10,7 +10,7 @@ from .testapp.models import (ModelWithVanillaMoneyField,
     ModelRelatedToModelWithMoney, ModelWithChoicesMoneyField, BaseModel, InheritedModel, InheritorModel,
     SimpleModel, NullMoneyFieldModel, ModelWithDefaultAsDecimal, ModelWithDefaultAsFloat, ModelWithDefaultAsInt,
     ModelWithDefaultAsString, ModelWithDefaultAsStringWithCurrency, ModelWithDefaultAsMoney, ModelWithTwoMoneyFields,
-    ProxyModel)
+    ProxyModel, ModelWithNonMoneyField)
 import moneyed
 
 
@@ -171,6 +171,15 @@ class RelatedModelsTestCase(TestCase):
         ModelRelatedToModelWithMoney.objects.get(moneyModel__money__lt=Money("1000.0", moneyed.ZWN))
 
 
+class NonMoneyTestCase(TestCase):
+
+    def testAllowExpressionNodesWithoutMoney(self):
+        """ allow querying on expression nodes that are not Money """
+        ModelWithNonMoneyField(money=Money(100.0), desc="hundred").save()
+        instance = ModelWithNonMoneyField.objects.filter(desc=F("desc")).get()
+        self.assertEqual(instance.desc, "hundred")
+
+
 class InheritedModelTestCase(TestCase):
     """Test inheritence from a concrete model"""
 
diff --git a/djmoney/tests/testapp/models.py b/djmoney/tests/testapp/models.py
index 8a91882..aeb64c6 100644
--- a/djmoney/tests/testapp/models.py
+++ b/djmoney/tests/testapp/models.py
@@ -51,6 +51,11 @@ class ModelWithChoicesMoneyField(models.Model):
     )
 
 
+class ModelWithNonMoneyField(models.Model):
+    money = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
+    desc = models.CharField(max_length=10)
+
+
 class AbstractModel(models.Model):
     price1 = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
```

```
FieldError: Cannot resolve keyword 'desc_currency' into field. Choices are: desc, id, money, money_currency
```

**Comment by benjaoming** [comment]
Thanks for this! Looks pretty convincing :) Can you make a PR with the failing test case and perhaps work out a way to fix it?

**Comment by AlexRiina** [comment]
Sorry for the delay: I just saw your response.

**Comment by benjaoming** [comment]
Confirming that the test fails as it should :)

**Comment by benjaoming** [comment]
Bump... Anybody willing to work on this now that the test case is so well-specified?

**Comment by alexhayes** [comment]
Working on it, hoping to have a PR later today.

**Comment by benjaoming** [comment]
Awesome!

**Comment by AlexRiina** [comment]
Woohoo! @benjaoming is there any reason my PR hasn't been merged?

**Comment by alexhayes** [comment]
@AlexRiina your test will be in my PR - along with a bunch of others.

**Comment by alexhayes** [comment]
Ok, so to fix this is pretty hectic once you start taking into account Q objects embedded inside Q objects, embedded inside Q objects within the filter args... For example;

```python
MyModel.objects.filter(Q(Q(money=Money(0, 'USD'), desc='foo') | Q(desc='eggs')) | Q(desc='bar'), field2='asdf')
```

I have tests that pass for this but it should certainly be looked at!

Note also that we are working with non public Django API here for Django 1.4-1.7. For Django 1.8+ there is to be a public facing API however I haven't handled that, instead explicitly raising NotImplemenedError.

Essentially this all works by traversing the lookup relationship down to the field in question and ensuring it is indeed a money field, there is a slightly easier way that doesn't require traversing however I felt that it wasn't as fail safe.

**Comment by benjaoming** [comment]
@AlexRiina I'm just voluntarily merging stuff that looks good. Now I've merged it, but it means that tests will break which is kind of annoying to other people who might be working on stuff.

**Comment by alexhayes** [comment]
Pending any further discoveries I think my feature/101 branch fixes this issue however I'd be keen to hear your feedback @benjaoming - particularly around the change to the RELEVANT_QUERYSET_METHODS in e7b3a7872f417aff81863d032b39951d4ce06690

A little background... we are in our final testing phase for a large internal Django project that has moved to Django 1.7 - during this move we also decided to switch from python-money to django-money. My feature/101 branch is now passing all our internal tests.

In terms of the django-money tests note that I have not tested Python 2.6 or 3.2 and I also get a strange error from `moneyed.test_moneyed_classes.TestMoney.test_str`, as follows;

```
________ TestMoney.test_str________ 
self = <moneyed.test_moneyed_classes.TestMoney object at 0x7f0dfa8b6050>

    def test_str(self):
>       assert str(self.one_million_bucks) == 'US$1,000,000.00'
E       assert '$1,000,000.00' == 'US$1,000,000.00'
E         - $1,000,000.00
E         + US$1,000,000.00
E         ? ++
```

I don't seem to get the above failure when on @benjaoming master branch but haven't had time to look into it yet.

**Comment by benjaoming** [comment]
Quick note on Python 3.2... the u prefix for strings, u"", is illegal... I don't know if this is related somehow...

**Comment by benjaoming** [comment]
I won't be able to look at this for a substantial while... so a shout-out to whomever is out there?

**Comment by briankung** [comment]
@alexhayes I am new to Python and Django, so please correct me if I'm wrong, but it seems like the localization is the culprit for the failing tests. At first, my thought was that the `py-moneyed` dependency wasn't up to date, but then I saw that the tests were using the latest version, `0.5.0` in many cases, and `py-moneyed`'s tests were all passing. So that limited the problem to `django-money`. After a naive search for "US" didn't turn anything up, I noticed a `use_l10n` boolean. Switching that off in all cases caused the localization tests to fail, but it did away with prepending "US" to the string.

@benjaoming I am not sure what the behavior of `django-money` should be - should it prepend "US" to USD? In which case I imagine we would want to override the `py-moneyed` test.

**Comment by briankung** [comment]
Here are my test results for one of the environments:

```
py27-django16-pm05 create: /Users/briankung/workspace/python/django-money/.tox/py27-django16-pm05
py27-django16-pm05 installdeps: Django==1.6.8, django-reversion==1.8.5, py-moneyed==0.5.0, pytest-django>=2.3.0, south>=0.8.2
py27-django16-pm05 inst: /Users/briankung/workspace/python/django-money/.tox/dist/django-money-0.5.0.zip
py27-django16-pm05 installed: Django==1.6.8,django-money==0.5.0,django-reversion==1.8.5,py==1.4.27,py-moneyed==0.5.0,pytest==2.7.1,pytest-django==2.8.0,six==1.9.0,South==1.0.2
py27-django16-pm05 runtests: PYTHONHASHSEED='3074607382'
py27-django16-pm05 runtests: commands[0] | /Users/briankung/workspace/python/django-money/.tox/py27-django16-pm05/bin/python runtests.py
Creating test database for alias 'default'...
.............FFF..................
======================================================================
FAIL: testAsVar (djmoney.tests.tags_tests.MoneyLocalizeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 81, in testAsVar
    context={'money': Money(2.3, 'PLN')})
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 25, in assertTemplate
    self.assertEqual(t.render(c), result)
AssertionError: u'2.30 z\u0142' != u'2,30 z\u0142'

======================================================================
FAIL: testConvert (djmoney.tests.tags_tests.MoneyLocalizeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 99, in testConvert
    context={})
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 25, in assertTemplate
    self.assertEqual(t.render(c), result)
AssertionError: u'2.50 z\u0142' != u'2,50 z\u0142'

======================================================================
FAIL: testOnOff (djmoney.tests.tags_tests.MoneyLocalizeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 33, in testOnOff
    context={'money': Money(2.3, 'PLN')})
  File "/Users/briankung/workspace/python/django-money/djmoney/tests/tags_tests.py", line 25, in assertTemplate
    self.assertEqual(t.render(c), result)
AssertionError: u'2.30 z\u0142' != u'2,30 z\u0142'

----------------------------------------------------------------------
Ran 34 tests in 0.072s

FAILED (failures=3)
```
