### ISSUE TITLE
Set default currency

### ISSUE THREAD

**Issue by dtrinchet** [django-money/django-money#109]
Is there any way to set in our django project settings a default currency? I have tried to 'overwrite' DEFAULT_CURRENCY_CODE and DEFAULT_CURRENCY so that MoneyField and Money's constructor gets the value but it doesn't work since these vars are from moneyed. I could pass currency to the constructor but this not the idea. Thanks

**Comment by dtrinchet** [comment]
Thanks man :+1:

**Comment by benjaoming** [comment]
You're welcome :) Let me know if there's any problems!
