### ISSUE TITLE
_has_changed state incorrect

### ISSUE THREAD

**Issue by maxtepkeev** [django-money/django-money#112]
If you're just changing currency and leave the amount part intact, ``_has_changed`` returns False, which is not what one would expect.

**Comment by benjaoming** [comment]
Great, this should be fixed now :)

**Comment by benjaoming** [comment]
@reinbach I've bumped the version in the repo, also the README should be compatible with PyPi now. Would you do the honors? :)

**Comment by reinbach** [comment]
@benjaoming the honors have been done.

**Comment by benjaoming** [comment]
@reinbach super :)

Check out the new description! Did you put it manually or did PyPi detect the README.rst automatically?

**Comment by reinbach** [comment]
@benjaoming description looks great. README was automatically handled.
