### ISSUE TITLE
Broken readonly_fileds representation for some fields in Django==1.8

### ISSUE THREAD

**Issue by vmspike** [django-money/django-money#126]
in `./djmoney/__init__.py:53`
AdminReadonlyField.contents = djmoney_contents

This line brokes readonly_fileds representation for some fields like CharField with 'choices' (raw value instead of choice description), DateTimeField (not localizable, no timezone) etc.
Cause of this is not up to date function `djmoney_contents()` which is use `smart_unicode()` instead of `display_for_field()`.
I've not found necessary functional for djmoney in this function, so I suppose to remove it, or update if it's required for compatibility with previous versions of Django.

**Comment by benjaoming** [comment]
Not quite sure I fully understand your description. But please do post a PR for this, sounds problematic!

**Comment by Stranger6667** [comment]
This code was removed recently, so issue should be fixed now.
