### ISSUE TITLE
makemigrations: ValueError: Cannot serialize: 0 USD

### ISSUE THREAD

**Issue by humatic** [django-money/django-money#129]
It seems a recent version change for `py-moneyed` has caused `django-money` migrations to fail. I had a fresh python install with the following versions (causing an error):

`python 3.4`
`django 1.8.3`
`django-money 0.7.1`
`py-moneyed 0.6.0`

In order to fix the error, I had to downgrade to `py-moneyed 0.5.0`.

**Comment by humatic** [comment]
Oops, I just realized this is a duplicate of #128.

**Comment by benjaoming** [comment]
Thanks for noticing that, closing it again then :)
