### ISSUE TITLE
ValueError: Cannot serialize: 0 RUB (Django 1.8.4)

### ISSUE THREAD

**Issue by valericus** [django-money/django-money#132]
Hi. Faced with exception in subject while migration. My class looks like

```python
class Account(models.Model):
    title = models.CharField(_('account name'), max_length=255)
    parent = models.ForeignKey('self', verbose_name=_('Parent'),
                               blank=True, null=True)
    balance = MoneyField(_('balance'), max_digits=65, decimal_places=6,
                         default=moneyed.Money(0, 'RUB'))
```

When I do `manage.py makemigrations` I receive ValueError. I've tried to specify default, default_currency, none of them. Each time I have ValueError.

Do I do something wrong?

**Comment by LennyLip** [comment]
Надо было написать в каком месте возникает ValueError. 

Судя по либе https://github.com/limist/py-moneyed/blob/master/moneyed/classes.py#L71 
стоит попробовать написать например так:
default=moneyed.Money(Decimal('0.0'), 'RUB')

**Comment by valericus** [comment]
Круто, спасибо! :-D
