### ISSUE TITLE
Default current no longer works with py-moneyed 0.6.0

### ISSUE THREAD

**Issue by MatthewJohn** [django-money/django-money#137]
After an update from py-moneyed 0.5.0 to 0.6.0, the default currency appears to be broken.

**Comment by MatthewJohn** [comment]
I'm afraid I have not been able to determine whether this is a bug with django-money or py-moneyed

**Comment by MatthewJohn** [comment]
Sorry, after further investigation, it appears that this issue is purely related to py-moneyed

**Comment by benjaoming** [comment]
Actually, I just did an update to support setting the default currency in a django project env. I maintained the default as the one from pymoneyed -- would you advice that? Or should we just use some conventional default like 'USD' or Malawian Kwacha?

**Comment by MatthewJohn** [comment]
Sorry, when I say default, I mean the default set on the field, e.g. for a given model, I have a field defined:

    cost = MoneyField(max_digits=12, decimal_places=2, default_currency='GBP')

However, in the admin model, the default currency is not set in the select widget

**Comment by benjaoming** [comment]
what happens if you use a currency object? Like `moneyed.GBP` ?
