### ISSUE TITLE
Model._meta.get_fields is only present in Django>=1.8

### ISSUE THREAD

**Issue by toudi** [django-money/django-money#149]
In the serializers.py there is a following line:

```
 field_names = set(f.name for f in Model._meta.get_fields())
```

This code will not work unless Django is >= 1.8 and therefore one cannot load any fixtures in Django < 1.8

Could this line possibly be replaced by following?

```
field_names = set(f.name for f in Model._meta.fields)
```

cheers,
toudi

**Comment by browniebroke** [comment]
+1
