### ISSUE TITLE
Remove Decimal Precision From Formatting

### ISSUE THREAD

**Issue by edwinlunando** [django-money/django-money#154]
I do not want to use decimal precision for my formatting. Is there any way to do it? I tried to find at this repo and py-moneyed but cannot get a clean solution.

I want IDR 5.000,00 into IDR 5.000

Any idea?

**Comment by benjaoming** [comment]
django-money uses py-moneyed for formatting in the __unicode__ and __str__ functions, have a look:

`from moneyed.localization import _FORMATTER, format_money`

https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L149

This function actually accepts `decimal_places`, however this is not used by django-money. You could create a setting for it that defaults to `None`.

**Comment by edwinlunando** [comment]
A new pull request, then.

**Comment by edwinlunando** [comment]
In this code

```python
    def __unicode__(self):

        if self.__use_l10n():
            locale = self.__get_current_locale()
            if locale:
                return format_money(self, locale=locale)

        return format_money(self)
```

How to get the field `decimal_places`?

**Comment by benjaoming** [comment]
Have a look at djmoney.settings, there you should add the following:

```python
# Tells djmoney how many digits to use when converting to strings
DECIMAL_PLACES = getattr(settings, 'CURRENCY_DECIMAL_PLACES', 2)
```

In both `__unicode__` and `__str__`, you should change all the calls to `format_money`, adding this:

```python
    def __unicode__(self):

        if self.__use_l10n():
            locale = self.__get_current_locale()
            if locale:
                return format_money(self, locale=locale, decimal_places=settings.DECIMAL_PLACES)

        return format_money(self, decimal_places=settings.DECIMAL_PLACES)
```

Make note of the difference between django.conf.settings and djmoney.settings

Feel free to make a PR!

**Comment by Stranger6667** [comment]
Since #251 is merged to master, this issue could be closed.
