### ISSUE TITLE
How to update a model with F expression?

### ISSUE THREAD

**Issue by cardmaster** [django-money/django-money#155]
When I'm trying to do this (cost is an MoneyField)
costfv is a float value

```python
cost_entry.cost.amount = F('cost__amount') + costfv
```

I've got this strange exception:

C:\Python27\lib\site-packages\djmoney\models\fields.py in get_db_prep_save
cursor was run to line 328
```python
 return super(MoneyField, self).get_db_prep_save(value, connection) ...
```
```python
        setattr(cls, self.name, MoneyFieldProxy(self))
    def get_db_prep_save(self, value, connection):
        if isinstance(value, Expression):
            return value
        if isinstance(value, Money):
            value = value.amount
                    return super(MoneyField, self).get_db_prep_save(value, connection) ...
    def get_db_prep_lookup(self, lookup_type, value, connection,
                           prepared=False):
        if not lookup_type in SUPPORTED_LOOKUPS:
            raise NotSupportedLookup(lookup_type)
        value = self.get_db_prep_save(value, connection)
```
▶ Local vars
Variable	Value
connection \<django.db.backends.sqlite3.base.DatabaseWrapper object at 0x03CB7C70\>
self	\<djmoney.models.fields.MoneyField: cost\>
value \<CombinedExpression: F(cost__amount) + Value(0.383349809627)\>

**Comment by benjaoming** [comment]
This sounds familiar: #153 - could you tell perhaps if it's the same?

**Comment by toudi** [comment]
I have stumbled upon this issue just today and I have been able to use the 'F' statement, provided that I did a small patch to django-money:

```
diff --git a/djmoney/models/fields.py b/djmoney/models/fields.py
index fae2c93..b002146 100644
--- a/djmoney/models/fields.py
+++ b/djmoney/models/fields.py
@@ -199,7 +199,7 @@ class MoneyFieldProxy(object):
             setattr(obj, self.currency_field_name,
                     smart_unicode(value.currency))
         elif isinstance(value, BaseExpression):
-            if isinstance(value.children[1], Money):
+            if hasattr(value, 'children') and isinstance(value.children[1], Money):
                 value.children[1] = value.children[1].amount
             obj.__dict__[self.field.name] = value
         else:
```

I am then able to use the F expression like so:

```
amount = Money(10, 'PLN')
mymodel.balance = F('balance') + amount.amount
mymodel.save()
```

Of course this is not entirely the same since I have to manually check if the currencies are the same, but .. :)

**Comment by benjaoming** [comment]
That sounds plausible @toudi - could you send in a PR with the change, then we can see if it passes the tests?

**Comment by toudi** [comment]
sure, I'll give it a go :)

**Comment by toudi** [comment]
I think I have narrowed it down just a bit.

Please see here:

https://github.com/django/django/commit/f59fd15c4928caf3dfcbd50f6ab47be409a43b01#diff-fe637a3ec6af9cbe2ee87293000e7c82

with this commit, the ExpressionNode no longer has 'children' attribute. I think I should be able to create a proper patch to django-money which detects this as opposed to dirty hack which simply allows to use F()

I just need a bit of time :)
