### ISSUE TITLE
tox.ini

### ISSUE THREAD

**Issue by toudi** [django-money/django-money#159]
I just realized, that in the tox.ini there two issues:

1. Django-1.9 is specified, but is never mentioned in envlist.
2. Django-1.9 is hardcoded to 1.9b3, however Django-1.9 is currently out of beta.

Could we possibly do this instead?

```
diff --git a/tox.ini b/tox.ini
index f66e871..76cc65f 100644
--- a/tox.ini
+++ b/tox.ini
@@ -2,8 +2,8 @@
 envlist =
     py{26,27,py}-django{14,15,16}-pm{04,05},
     py{32,33}-django{15,16}-pm05,
-    py27-django{17,18,_master}-pm04,
-    py{32,33,34,py}-django{17,18,_master}-pm05,
+    py27-django{17,18,19,_master}-pm04,
+    py{32,33,34,py}-django{17,18,19,_master}-pm05,
 
 [testenv]
 basepython =
@@ -49,7 +49,7 @@ commands = {envpython} runtests.py {posargs}
        Django==1.8.2
        django-reversion==1.8.5
 1.9.x  =
-       Django==1.9b1
+       Django>=1.9,<1.10
        django-reversion==1.9.3
 master =
        https://github.com/django/django/tarball/master
```
Unfortunetely I'm no expert on tox, but the idea was to use the latest version of 1.9.x as opposed to some hard-coded release version.

cheers,

**Comment by benjaoming** [comment]
Thanks for reporting this!

**Comment by benjaoming** [comment]
Fixed in #160. You could try to rebase current master into your PRs to be sure that it's all okay?

**Comment by toudi** [comment]
sure, I can do that. Could you please tell me what about the pytest.ini ?
currently, it only allows just one test file to be executed. Is this
accidental, or a planned approach?

2016-01-06 13:52 GMT+01:00 benjaoming <notifications@github.com>:

> Fixed in #160 <https://github.com/django-money/django-money/pull/160>.
> You could try to rebase current master into your PRs to be sure that it's
> all okay?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-money/django-money/issues/159#issuecomment-169317141>
> .
>



-- 
pozdrawiam serdecznie,
Mateusz Mikołajczyk, a.k.a. toudi

**Comment by benjaoming** [comment]
@toudi can you explain what you want to do, maybe I can help? :)

**Comment by toudi** [comment]
well, my point is that if you look into the djmoney/tests directory, there are several files with tests. However, they are skipped during the tests execution because in the pytest.ini there curently is only one entry:

`python_files=mone*.py`

which means that only one file fits this regexp: money_patched.py

That's why I asked whether this is a desired entry, or we should add another entries so that the other files get picked up, or we could also rename all the `tests/*.py` files to match money prefix ;)
