### ISSUE TITLE
Django-money failing on production server with weird error

### ISSUE THREAD

**Issue by gabn88** [django-money/django-money#163]
I have used django-money for already a long time. A few weeks ago I upgraded to python3.4(.4) and Django 1.8.7 and now I got the following error:

I removed Django-money and now my server is up again. However I would like to use django-money!

[Fri Jan 08 17:24:23.650297 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] mod_wsgi (pid=955398): Target WSGI script '/home/production/framework/$
[Fri Jan 08 17:24:23.650353 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] mod_wsgi (pid=955398): Exception occurred processing WSGI script '/home/production_v$
[Fri Jan 08 17:24:23.650395 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] Traceback (most recent call last):
[Fri Jan 08 17:24:23.650585 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/Python34/lib/python3.4/xml/sax/expatreader.py", line 22, in <module>
[Fri Jan 08 17:24:23.650594 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     from xml.parsers import expat
[Fri Jan 08 17:24:23.650678 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/Python34/lib/python3.4/xml/parsers/expat.py", line 4, in <module>
[Fri Jan 08 17:24:23.650686 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     from pyexpat import *
[Fri Jan 08 17:24:23.650710 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] ImportError: /home/Python34/lib/python3.4/lib-dynload/pyexpat.cpython-34m.so: undefined symb$
[Fri Jan 08 17:24:23.650725 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]
[Fri Jan 08 17:24:23.650730 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] During handling of the above exception, another exception occurred:
[Fri Jan 08 17:24:23.650733 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]
[Fri Jan 08 17:24:23.650743 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] Traceback (most recent call last):
[Fri Jan 08 17:24:23.650834 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/production/framework/framework/wsgi.py", line 14, in <mo$
[Fri Jan 08 17:24:23.650842 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     application = get_wsgi_application()
[Fri Jan 08 17:24:23.650925 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/core/wsgi.py", line 1$
[Fri Jan 08 17:24:23.650933 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     django.setup()
[Fri Jan 08 17:24:23.651018 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/__init__.py", line 18$
[Fri Jan 08 17:24:23.651025 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     apps.populate(settings.INSTALLED_APPS)
[Fri Jan 08 17:24:23.651174 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/apps/registry.py", li$
[Fri Jan 08 17:24:23.651182 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     app_config.import_models(all_models)
[Fri Jan 08 17:24:23.651300 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/apps/config.py", line$
[Fri Jan 08 17:24:23.651307 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     self.models_module = import_module(models_module_name)
[Fri Jan 08 17:24:23.651412 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/Python34/lib/python3.4/importlib/__init__.py", line 109, in import_module
[Fri Jan 08 17:24:23.651420 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jan 08 17:24:23.651436 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
[Fri Jan 08 17:24:23.651452 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
[Fri Jan 08 17:24:23.651475 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
[Fri Jan 08 17:24:23.651491 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
[Fri Jan 08 17:24:23.651508 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 1129, in _exec
[Fri Jan 08 17:24:23.651524 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 1471, in exec_module
[Fri Jan 08 17:24:23.651542 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
[Fri Jan 08 17:24:23.651660 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/production/billing/customer_billing/models.py", line 18,$
[Fri Jan 08 17:24:23.651668 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     from djmoney.models.fields import MoneyField
[Fri Jan 08 17:24:23.651749 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/djmoney/models/__init__.py",$
[Fri Jan 08 17:24:23.651756 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     serializers.register_serializer("json", 'djmoney.serializers')
[Fri Jan 08 17:24:23.651873 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:23.651881 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     _load_serializers()
[Fri Jan 08 17:24:23.651906 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:23.651912 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     register_serializer(format, BUILTIN_SERIALIZERS[format], serializers)
[Fri Jan 08 17:24:23.651933 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:23.651939 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     module = importlib.import_module(serializer_module)
[Fri Jan 08 17:24:23.651964 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/Python34/lib/python3.4/importlib/__init__.py", line 109, in import_module
[Fri Jan 08 17:24:23.651970 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jan 08 17:24:23.652112 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/lib/python3.4/site-packages/django/core/serializers/xml_$
[Fri Jan 08 17:24:23.652120 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     from xml.sax.expatreader import ExpatParser as _ExpatParser
[Fri Jan 08 17:24:23.652144 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]   File "/home/Python34/lib/python3.4/xml/sax/expatreader.py", line 24, in <module>
[Fri Jan 08 17:24:23.652150 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731]     raise SAXReaderNotAvailable("expat not supported", None)
[Fri Jan 08 17:24:23.652173 2016] [wsgi:error] [pid 955398:tid 140166047684352] [remote 127.0.0.1:31731] xml.sax._exceptions.SAXReaderNotAvailable: expat not supported
[Fri Jan 08 17:24:24.810863 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] mod_wsgi (pid=955397): Target WSGI script '/home/production/framework/$
[Fri Jan 08 17:24:24.810920 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] mod_wsgi (pid=955397): Exception occurred processing WSGI script '/home/production_v$
[Fri Jan 08 17:24:24.839629 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] Traceback (most recent call last):
[Fri Jan 08 17:24:24.839985 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/Python34/lib/python3.4/xml/sax/expatreader.py", line 22, in <module>
[Fri Jan 08 17:24:24.839993 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     from xml.parsers import expat
[Fri Jan 08 17:24:24.840080 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/Python34/lib/python3.4/xml/parsers/expat.py", line 4, in <module>
[Fri Jan 08 17:24:24.840087 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     from pyexpat import *
[Fri Jan 08 17:24:24.840113 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] ImportError: /home/Python34/lib/python3.4/lib-dynload/pyexpat.cpython-34m.so: undefined symb$
[Fri Jan 08 17:24:24.840129 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]
[Fri Jan 08 17:24:24.840133 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] During handling of the above exception, another exception occurred:
[Fri Jan 08 17:24:24.840136 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]
[Fri Jan 08 17:24:24.840148 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] Traceback (most recent call last):
[Fri Jan 08 17:24:24.840265 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/production/framework/framework/wsgi.py", line 14, in <mo$
[Fri Jan 08 17:24:24.840273 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     application = get_wsgi_application()
[Fri Jan 08 17:24:24.840360 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/core/wsgi.py", line 1$
[Fri Jan 08 17:24:24.840368 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     django.setup()
[Fri Jan 08 17:24:24.840449 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/__init__.py", line 18$
[Fri Jan 08 17:24:24.840456 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     apps.populate(settings.INSTALLED_APPS)
[Fri Jan 08 17:24:24.840606 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/apps/registry.py", li$
[Fri Jan 08 17:24:24.840613 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     app_config.import_models(all_models)

[Fri Jan 08 17:24:24.840736 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/apps/config.py", line$
[Fri Jan 08 17:24:24.840744 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     self.models_module = import_module(models_module_name)
[Fri Jan 08 17:24:24.840850 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/Python34/lib/python3.4/importlib/__init__.py", line 109, in import_module
[Fri Jan 08 17:24:24.840863 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jan 08 17:24:24.840881 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
[Fri Jan 08 17:24:24.840897 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
[Fri Jan 08 17:24:24.840913 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
[Fri Jan 08 17:24:24.840928 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
[Fri Jan 08 17:24:24.840946 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 1129, in _exec
[Fri Jan 08 17:24:24.840968 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 1471, in exec_module
[Fri Jan 08 17:24:24.840988 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
[Fri Jan 08 17:24:24.841110 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/production/billing/customer_billing/models.py", line 18,$
[Fri Jan 08 17:24:24.841117 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     from djmoney.models.fields import MoneyField
[Fri Jan 08 17:24:24.841195 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/djmoney/models/__init__.py",$
[Fri Jan 08 17:24:24.841202 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     serializers.register_serializer("json", 'djmoney.serializers')
[Fri Jan 08 17:24:24.841322 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:24.841329 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     _load_serializers()
[Fri Jan 08 17:24:24.841355 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:24.841361 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     register_serializer(format, BUILTIN_SERIALIZERS[format], serializers)
[Fri Jan 08 17:24:24.841383 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/core/serializers/__in$
[Fri Jan 08 17:24:24.841389 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     module = importlib.import_module(serializer_module)
[Fri Jan 08 17:24:24.841411 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/Python34/lib/python3.4/importlib/__init__.py", line 109, in import_module
[Fri Jan 08 17:24:24.841416 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jan 08 17:24:24.841560 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/lib/python3.4/site-packages/django/core/serializers/xml_$
[Fri Jan 08 17:24:24.841571 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     from xml.sax.expatreader import ExpatParser as _ExpatParser
[Fri Jan 08 17:24:24.841595 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]   File "/home/Python34/lib/python3.4/xml/sax/expatreader.py", line 24, in <module>
[Fri Jan 08 17:24:24.841601 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306]     raise SAXReaderNotAvailable("expat not supported", None)
[Fri Jan 08 17:24:24.841620 2016] [wsgi:error] [pid 955397:tid 140166037194496] [remote 127.0.0.1:56306] xml.sax._exceptions.SAXReaderNotAvailable: expat not supported

**Comment by benjaoming** [comment]
Dude, that traceback is totally unreadable :)

Have a look at the other issues for 1.8 and please try to be more specific so it's possible to tell what problem you're running into.

There's already PRs for 1.8 open that will be coming in soonish.
