### ISSUE TITLE
Updating the currency of an existing object fails

### ISSUE THREAD

**Issue by Hedde** [django-money/django-money#172]
We are trying to update the currency of an existing object (django-money 0.7.6), this fails because of a specific check in the set method, what is the idea of this check?

    def __set__(self, obj, value):
        if isinstance(value, tuple):
            value = Money(amount=value[0], currency=value[1])
        if isinstance(value, Money):
            obj.__dict__[self.field.name] = value.amount
            # we have to determine whether to replace the currency.
            # i.e. if we do the following:
            # .objects.get_or_create(money_currency='EUR')
            # then the currency is already set up, before this code hits
            # __set__ of MoneyField. This is because the currency field
            # has less creation counter than money field.
            obj_curr = obj.__dict__[self.currency_field_name]
            val_curr = str(value.currency)
            def_curr = str(self.field.default_currency)
            if obj_curr != val_curr:
                # in other words, update the currency only if it wasn't
                # changed before.
                if obj_curr == def_curr:   # <=== why ????
                setattr(
                    obj, self.currency_field_name,
                    smart_unicode(value.currency))

**Comment by Stranger6667** [comment]
@benjaoming can you advice on that? What suppose to be expected here?
If we want to change the money value of an existing object. IMO:
1. In all cases, when the currency is explicitly set - provided value should be used. No matter what kind of operation it is.
2. If there is no value for currency field, then default currency should be used

**Comment by benjaoming** [comment]
I would agree to your list! And also that the above code seems like it was written in a rush, hard to understand what the intention of the check is.

**Comment by Stranger6667** [comment]
@Hedde , could you check the issue with the latest version of `django-money`? It is not on PyPI yet, but this behavior was fixed few commits ago

**Comment by andir** [comment]
I've tried with the pending 0.8 release branch from @Stranger6667 and with the current master. Both seem to revert to the previous currency once I do a full clean on my model.

My test case looks similar to
```python
obj = AccountFactory()
obj.amount # is the Moneyfield
# change from default currency (USD) to AUD
obj.amount.currency = moneyed.Currency(code='AUD')
obj.full_clean()
# afterwards this fails
assert obj.amount.currency.code == 'AUD'
# this succeeds...
assert obj.amount.currency.code == 'USD'
```

**Comment by Stranger6667** [comment]
Thank you for the report!
Could you please tell which Django version did you use?

**Comment by andir** [comment]
django 1.9

**Comment by Stranger6667** [comment]
You can use the following code:
```
obj.amount_currency = moneyed.Currency(code='AUD')
```

Unfortunately when you are using ```amount.currency``` you modifies ```MoneyPatched``` object, which doesn't know about money field at all. It is possible to implement such behavior, but it moves ```MoneyPatched``` too far away from original ```Money``` class.
I think, that may be it worth to have our own implementation of ```Money```, but it is a bit out of the current scope

**Comment by andir** [comment]
Well that would work for me. Is this behaviour documented somewhere?

**Comment by Guest007** [comment]
It's very strange behavior. I can change currency as I want. BUT I can't return to default value. Why? It's illogically.
As I understand lifehack in pointing rare or unused currency by default.

**Comment by Stranger6667** [comment]
@andir 
Sorry for so late response, but no, this behaviour is not documented :( Feel free to open PR to improve our documentation :)

**Comment by Stranger6667** [comment]
@Guest007 
Sorry, could you clarify what do you mean? Do you mean the behavior from @Hedde message? Or from @andir message?

**Comment by Guest007** [comment]
@Stranger6667 
1) I have default value USD
2) create a record.
3) change record and set another currency, EUR, for example
4) Understand big mistake and try to change back to default USD. AND WE CAN'T DO THAT!!!! 
all other currency except return to default. I want my USD back! How? This is my question.

**Comment by benjaoming** [comment]
@Guest007 - where? In the Django Admin interface?

Also, you're commenting on a closed issue. Is this supposed to be related with the above issue or its PR fix?

**Comment by Stranger6667** [comment]
Now it should work :) I close this issue
