### ISSUE TITLE
Django REST Framework support

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#179]
I propose to add `MoneyField` for Django REST Framework. It can be a useful feature IMO.
E.g.

```python
from rest_framework import serializers
from djmoney.extra.drf import MoneyField

class AccountSerializer(serializers.ModelSerializer):
    amount = MoneyField()

```

And `Money` instances will be de/serialized properly. Also I think it is possible to register this `MoneyField` directly in `ModelSerializer. serializer_field_mapping `, but I'm not sure about it for now.

I'll try to submit PR for that

**Comment by benjaoming** [comment]
:+1:

**Comment by miclovich** [comment]
:+1: Looking forward to seeing a nice serializer for this.

**Comment by godardth** [comment]
Hi,

I am using something like that, hope it can help.

```
from moneyed import Money
from rest_framework import serializers
from accounting.models import Account

class MoneyField(serializers.Field):
    def to_representation(self, obj):
        return {
            'amount': "%f" % (obj.amount),
            'currency': "%s" % (obj.currency),
        }
    def to_internal_value(self, data):
        return Money(data['amount'], data['currency'])

class AccountSerializer(serializers.ModelSerializer):
    balance = MoneyField()
    class Meta:
        model = Account
```

**Comment by miclovich** [comment]
Looks solid. Will test it out.

**Comment by Guest007** [comment]
In this variant of serializer currency already 'XYZ'.

**Comment by Stranger6667** [comment]
#205 is merged to master branch. I'll add documentation in the next few days

**Comment by elcolie** [comment]
Any progress on the next release?

**Comment by benjaoming** [comment]
@elcolie you're commenting on a closed issue!

Here's a link to the Changelog:

http://django-money.readthedocs.io/en/stable/changes.html
