### ISSUE TITLE
Problem trying to create an instance with objects.create

### ISSUE THREAD

**Issue by jlariza** [django-money/django-money#181]
Hi!

I'm trying to create an instance of a model with MoneyField in it with objects.create, it return the object but the database is never written. 

I have two models with MoneyField and with the both of them I'm having that issue.

I also tried instantiating the model, writing each field manually and then using .save() method; it did not work either.

Thank you

**Comment by Stranger6667** [comment]
Hello, could you, please, provide your models here, and may be some code to reproduce this error?
Also, what version of django-money do you use?

**Comment by jlariza** [comment]
Hi! 

I just find out that the problem is because I'm creating the object inside an APIView of DjangoRestFramework; When I create it in a normal View, it gets written in the database.

I'll keep investigating

**Comment by jlariza** [comment]
Hi!
I just find out the issue. The problem was that when working with djangoRestFramework and the transaction where the view is executed fails (It does not return a status related with success), the transaction is deleted and the objects is never created.

At the end it did not have relation with django money. Thank you for your time. I am closing the issue
