### ISSUE TITLE
Bug in fields caching

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#186]
`get_field_by_name` should return field instance as first argument.

It is True
```python
InheritorModel._meta.get_field_by_name('money_currency')[0].__class__.__name__ == 'CurrencyField'
```

But the same code returns different result if this was called before:
```python
InheritorModel._meta.get_field_by_name('money')
```

It works in a reverse way. If `get_field_by_name` was called with `money_currency` before, then for `money` `CurrencyField` will be returned instead of `MoneyField`.

This bug is related with caching in Django 1.8+

I'll submit PR on this.

**Comment by benjaoming** [comment]
Awesome!
