### ISSUE TITLE
A model with multiple MoneyField sharing a single currency?

### ISSUE THREAD

**Issue by drdaeman** [django-money/django-money#195]
I have a model where there are multiple amounts, which must all be in a same single currency. I know I can just throw in multiple `MoneyFields` and ensure the consistency in `Model.clean`, but this would create unnecessarily many database fields, which I don't like. I could've also used plain and simple `DecimalField`s, but since I plan to use `Money` objects everywhere I want consistency in this regard (and don't want to construct those explicitly everywhere I need the field's value).

From what I understood from reading the source code, currently `MoneyField` always automatically creates paired `CurrencyField` and there's no control over this.

I wonder if a field type, or an extension of `MoneyField`'s API that'd use explicitly-created `CurrencyField` would be a good addition. I.e.:

```
class Invoice(models.Model):
    currency = CurrencyField(...)
    total = MoneyField(..., currency_field_name="currency")
    paid = MoneyField(..., currency_field_name="currency")
    ...
```

In this scenario, to keep things simple and avoid unexpected bugs, assigning a value with a mismatching currency should probably result in an exception:

```
# This should fail and raise ValueError (or a subclass of it)
invoice = Invoice(currency=USD, total=Money(10, USD), paid=Money(0, EUR), ...)

invoice = Invoice(currency=USD, total=Money(10, USD), paid=Money(0, USD), ...)
invoice.paid = Money(5, USD)      # This is OK
invoice.paid = Money(8.79, EUR)   # This should fail
```

I had a limited success by subclassing and overriding `contribute_to_class` to return a specially prepared `MoneyFieldProxy` ([gist with my kludge that happens to work for me](https://gist.github.com/drdaeman/5d1a948e829ceb78af7afce701378545)), but it only works seemingly correctly if `CurrencyField` is properly listed above any dependent fields.

What do you think? Is something like this a good idea?

Thanks!

**Comment by Stranger6667** [comment]
Hi @drdaeman ! 
Sorry for the long silence. To me it seems like an interesting feature, that is not hard to implement. I'll take a look in the next couple of weeks, probably, it could be done in the next major release (0.12).

Regards.

**Comment by Stranger6667** [comment]
Yes, I'm interested :) I had no time to check everything, but I think, that we can postpone some refactoring. So, it is ready to review :)
