### ISSUE TITLE
Auto conversion of currency is a really bad default, plus you can't change it

### ISSUE THREAD

**Issue by spookylukey** [django-money/django-money#199]
I'm talking about the behaviour added here:

https://github.com/django-money/django-money/commit/edfc25a5aa46a605f27d15b891bfae28b74cb5db

which I discovered when upgrading from 0.7.2

Can I persuade you this is a really bad idea? I think it is a very bad idea for any auto-conversion to be built into the money class at all, but having it on by default, and without a way to turn it off is really really bad, because:

1) currency conversion is not a lossless process. You simply can't "compare" two objects in different currencies, nor add them, or subtract them. You can't "compare" potatoes to tomatoes simply because you can use one to buy the other, and for the same reason you can't do the same with currencies, because the price changes all the time. In fact, even at a single point in time there is not one answer - there are many answers, different bodies will trade the commodity at different prices. Exchange rate indexes are just averages.

In addition to changing market exchange rates, there could be any number of additional things you want to do when changing currency. For example, because of rate changes, it's entirely possible that what someone was supposed to pay is no longer the 'right' price. You need to have a strategy for coping with that (e.g. rounding a bit) and silent currency conversions add confusion not help.

Instead, if you want to compare currencies in any way, you should be explicitly doing a conversion. "Explicit is better than implicit" etc. As Python matures, it always gets closer to that ideal e.g. byte strings and unicode cannot be compared in Python 3.

In this way, if you accidentally compare or add two money objects of different currencies, you made a mistake as a developer, and should be informed with a loud exception.

2) You are changing the behaviour of another library.

With plain py-moneyed, as above, you get the desired behaviour:

    >>> Money(10, GBP) > Money(10, USD)
    TypeError: Cannot compare Money with different currencies.

    >>> Money(10, GBP) + Money(10, USD)
    TypeError: Cannot add or subtract two Money instances with different currencies.

It's extremely surprising when django-money doesn't behave the same way, when it is supposed to be built on top of it, and is advertised as such. This exception is extremely important part of how py-moneyed works and what I depend on for ensuring correctness of my app. I happen to use djmoney_rates too, but only ever with explicit conversions.

This is also a really big change from 0.7.2, when it did behave the same as py-moneyed.

3) currency conversion introduces rounding that you didn't ask for, even if the currencies are the same - see https://github.com/evonove/django-money-rates/blob/master/djmoney_rates/utils.py#L55

4) currency conversion kicks off IO! It calls djmoney-rates which calls get_rate_source(), which does DB work, and potentially any kind of DB/network in order to get rates, depending on the backend. So instead of being a pure function, we get network/disk etc., including potential failures because of that.

5) due to implementation of djmoney-rates, this happens even if no conversion is involved - get_rate_source() is called when you are converting to the same currency! This is a massive performance and reliability hit.

A quick check on my machine shows that adding two MoneyPatched instances has gone from 11.1 microseconds in 0.7.2 to 2.8 milliseconds i.e. 250 times slower, including 5 DB queries for *EVERY* money comparison/sum, including ones that require NO conversion because they are in the same currency! And this is in the best case when the rates have already been fetched over the network, and the database has warmed up and is in the OS cache etc.

At the very least, the feature should be selected with a setting, which should default to False. I would argue the feature should be removed entirely - if you are dealing with money, you will *always* want to be explicit about conversions. There may be a few extremely simple use cases where the strategy of auto conversion is good enough, but a generic money app should not be doing that.

**Comment by spookylukey** [comment]
I'm going to interpret the thumbs up from @benjaoming as "go ahead and make a patch that changes the default behaviour", which I will hopefully do shortly.

**Comment by benjaoming** [comment]
Yes @spookylukey after reading it, I may have been short of words about how good your statement of intent and motivation was :)

Something is always a good idea until someone else comes and has a better one. You did!

Giant thumbs up!

**Comment by Stranger6667** [comment]
PR is merged into master branch.
