### ISSUE TITLE
Stop importing stuff in djmoney/__init__.py

### ISSUE THREAD

**Issue by benjaoming** [django-money/django-money#208]
By convention, it's a bad idea to have imports here as it risks breaking stuff at load time.

Related:
#89 
#102

@Stranger6667 reported:

> IMO it is a bad thing - to import models on module level. In some cases it leads to "app registry is not ready" errors.
> I faced with this in #205 - I can't import MoneyField in djmoney/__init__.py, but it is required to import it at this stage to get automatically registered MoneyField for DRF :(

**Comment by Stranger6667** [comment]
At first glance removal of code in ``__init__.py`` doesn't change anything in admin. I checked Django 1.7-1.9, so possibly it will be very simple changes

**Comment by Stranger6667** [comment]
Commit date is 28.09.2012, so it is can be related only to Django 1.3 - 1.4

**Comment by Stranger6667** [comment]
So, it doesn't change anything even on Django 1.4
![django1 4](https://cloud.githubusercontent.com/assets/1236561/16647419/5f749900-442f-11e6-9940-1c9bacb1daa4.png)

**Comment by Stranger6667** [comment]
So I'll just remove this code and add version attribute
