### ISSUE TITLE
How to set custom name for currency for dropdownbox?

### ISSUE THREAD

**Issue by ChessSpider** [django-money/django-money#211]
Hi, 

In the dropdownbox I just want to show USD, EUR, etc. But I couldnt find how to do it.

Instead I changed the djmoney\settings.py into this:

``` python
if PROJECT_CURRENCIES:
    try:
        CURRENCY_CHOICES = [(CURRENCIES[code].code, name) for (code, name) in PROJECT_CURRENCIES]
    except (ValueError, TypeError):
        CURRENCY_CHOICES = [(code, CURRENCIES[code].name) for code in PROJECT_CURRENCIES]
else:
    CURRENCY_CHOICES = [(c.code, c.name) for i, c in CURRENCIES.items() if
                        c.code != DEFAULT_CURRENCY_CODE]
```

And made the CURRENCIES setting a tuple:

``` python
CURRENCIES = (('EUR', 'EUR €'), ('USD', 'USD $'))
```

but is there an official way to set it on a project-level?

**Comment by Stranger6667** [comment]
You can do it like this:

```
CURRENCIES = ['USD', 'EUR']
```

And ``CURRENCY_CHOICES`` will be ``[('EUR', 'Euro'), ('USD', 'US Dollar')]``

Is this what you want?

**Comment by ChessSpider** [comment]
lol, of course. Thx !

**Comment by Stranger6667** [comment]
You're welcome :)

**Comment by ChessSpider** [comment]
Actually, i didn work :(

djmoney/settings.py: 
```python
# The default currency choices, you can define this in your project's
# settings module
PROJECT_CURRENCIES = getattr(settings, 'CURRENCIES', None)

if PROJECT_CURRENCIES:
    CURRENCY_CHOICES = [(code, CURRENCIES[code].name) for code in PROJECT_CURRENCIES]
else:
    CURRENCY_CHOICES = [(c.code, c.name) for i, c in CURRENCIES.items() if
                        c.code != DEFAULT_CURRENCY_CODE]

CURRENCY_CHOICES.sort(key=operator.itemgetter(1, 0))

```

Doesn't the above logic overwrite my custom CURRENCY_CHOICES in the projects' settings.py?

**Comment by Stranger6667** [comment]
No, it will be only used in ``django-money/settings.py``. Can you tell what exactly didn't work and what is your expectations?

**Comment by ChessSpider** [comment]
Yeah I don't really want to change django-money/settings.py, as I'm using heroku which just fetches the dependancies from requirements.txt via pip. I can change the dependancy, put it on github, etc.. but honestly its a bit of a pain

I guess I just want to set CURRENCY_CHOICES from my own main project's settings.py :), like the way I can set the PROJECT_CURRENCIES setting by defining CURRENCIES.

**Comment by ChessSpider** [comment]
I guess this may be enough (untested, and I'm tired):

```python
PROJECT_CURRENCIES = getattr(settings, 'CURRENCIES', None)
CURRENCY_CHOICES = getattr(settings, 'CUSTOM_CURRENCY_CHOICES', None)

if CURRENCY_CHOICES is not None:
        CURRENCY_CHOICES = [(CURRENCIES[code].code, name) for (code, name) in CURRENCY_CHOICES]
elif PROJECT_CURRENCIES and CURRENCY_CHOICES is None:
    CURRENCY_CHOICES = [(code, CURRENCIES[code].name) for code in PROJECT_CURRENCIES]
else:
    CURRENCY_CHOICES = [(c.code, c.name) for i, c in CURRENCIES.items() if
                        c.code != DEFAULT_CURRENCY_CODE]

CURRENCY_CHOICES.sort(key=operator.itemgetter(1, 0))
```

**Comment by ChessSpider** [comment]
and then put this in my main projects settings.py:

```python 
DEFAULT_CURRENCY = 'EUR'
CURRENCIES = ('EUR', 'USD', 'AED', )
CURRENCY_CHOICES = (('EUR', 'EUR €'), ('USD', 'USD $'), ('AED', 'AED د.إ'), )
```

**Comment by ChessSpider** [comment]
Hi guys!

Just writing to inform that there's an error in the example:
```
CURRENCIES = ('USD', 'EUR')
CURRENCY_CHOICES = (('USD', 'USD $'), ('EUR', 'EUR €'))
```
does not work, it gives an error on the sort of CURRENCY_CHOICES:

```
 File "D:\podictive\PyPulseJam\venv\lib\site-packages\djmoney\settings.py", line 26, in <module>
    CURRENCY_CHOICES.sort(key=operator.itemgetter(1, 0))
AttributeError: 'tuple' object has no attribute 'sort'
```

I changed it to a list [] and that fixed it

However I don't think you should do a sort.. As the user is explicitly naming the currencies and their options, including their order. I don't expect the system to change the order.
