### ISSUE TITLE
Create a documentation

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#219]
At this moment some areas are not documented at all, e.g. REST Framework support or complex queries

**Comment by Stranger6667** [comment]
@benjaoming hi!
What do you think about putting django-money documentation to readthedocs?

**Comment by benjaoming** [comment]
I think that's a brilliant idea and should have been done a long time ago :) First step is just to copy the current README!

One thing that I like is to be DRY.. meaning that you can put `docs/index.rst` and in there, you can link the contents of `../README.rst`. It's a pattern I saw on cookiecutter...

**Comment by Stranger6667** [comment]
Thanks! I pushed some work - #234 . Let's continue our discussion in that PR :)

**Comment by benjaoming** [comment]
The docs are up and active, and there are other separate issues tracking specific new sections to add, so closing this.

Great work!! :tada:
