### ISSUE TITLE
After changing a currency field, it can't be changed back to it's default_currency

### ISSUE THREAD

**Issue by caolan** [django-money/django-money#221]
Thanks to this line: https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L264

**Comment by benjaoming** [comment]
Haha, this issue is funny...

A PR is welcome!

**Comment by caolan** [comment]
I'm not entirely sure what that test is supposed to be doing, so it would be good if someone else can take a look at it.

**Comment by benjaoming** [comment]
Now this issue has stopped being funny :)

**Comment by Stranger6667** [comment]
Can we close it now?

**Comment by benjaoming** [comment]
Yes! :) Thanks for reporting @caolan

**Comment by caolan** [comment]
Thanks for fixing this @benjaoming - much appreciated!

**Comment by noam-fairfly** [comment]
Awesome! When to you plan to release this fix?

**Comment by benjaoming** [comment]
@noam-fairfly good question, I remember that this or some other bug/pr caused us to wanna bump the next version to 0.10 - there's also a PR with some docs. Maybe when the docs PR is finished, and we have docs+release notes on ReadTheDocs, we should release... hoping that doesn't complicate it too much.

NB! You can always install the master branch directly via dependency links in your requirements.txt

**Comment by noam-fairfly** [comment]
Hey @benjaoming, I see there are no PR opened. Time to bump a new version? 📦

**Comment by benjaoming** [comment]
Hi @noam-fairfly - true, actually a lot of PRs have been merged since then by @Stranger6667 

Is the current `master` releasable @Stranger6667 ? Are releases ready?

In that case, I'll bump version and put it on PyPi...

**Comment by Stranger6667** [comment]
Hello, @benjaoming !
I'm pretty sure, that we're ready for next release :)

**Comment by benjaoming** [comment]
The version was already bumped to `0.10` - for future reference, it's better to bump version to something like `0.10dev`, otherwise people who have installed from `master` will not detect that the PyPi version is updated.

**Comment by benjaoming** [comment]
It's released :)
