### ISSUE TITLE
django-money does not work in django 1.10.1 (works in 1.10)

### ISSUE THREAD

**Issue by listingmirror** [django-money/django-money#222]
In DJango 1.10.1 with django-money==0.9.1

Have a simple model and model_form

```
class Foo(models.Model):
    foo_id = models.AutoField(primary_key=True)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')

class FooForm(forms.ModelForm):
    prefix = 'my_foo_form'

    class Meta:
        model = Foo
        fields = 'price'
```

If I do a create with this, all is well. But if I do an edit - all fields except price save. Price does not save to the database.

I debugged through it a few times. price showed up in modified fields.. and then it didn't..  need to dig deeper to figure out what is going on though.

If I replace the money field with a straight decimal field... everything is good.

**Comment by listingmirror** [comment]
Example failing unit test

```
def test_save_and_update():
    money = Money(Decimal('200'), moneyed.SEK)
    form = MoneyModelForm({'money_0': money.amount, 'money_1': money.currency})

    assert form.is_valid()
    instance = form.save()
    retrieved = ModelWithVanillaMoneyField.objects.get(pk=instance.pk)

    money_2 = Money(Decimal('123'), moneyed.SEK)
    form_2 = MoneyModelForm(data={'money_0': money_2.amount, 'money_1': money_2.currency}, instance=retrieved)

    assert form_2.is_valid()
    instance_2 = form_2.save()
    retrieved_2 = ModelWithVanillaMoneyField.objects.get(pk=instance_2.pk)
    assert money_2 == instance_2.money
    assert money_2 == retrieved_2.money

```

**Comment by listingmirror** [comment]
Perhaps it is this

https://code.djangoproject.com/ticket/27220

**Comment by listingmirror** [comment]
Confirm bug in Django 1.10.1... fixed in either Django 1.10.0 or Django master.

**Comment by Stranger6667** [comment]
Hello, thank you for the report!
I'll investigate this issue

**Comment by benjaoming** [comment]
The bug in Django 1.10.1 is fixed here, and they expect 1.10.2 to ship around October 1st: https://github.com/django/django/pull/7217

**Comment by listingmirror** [comment]
Confirmed the patch works on a local forked Django

**Comment by listingmirror** [comment]
Perhaps we should add a documention line "Confirmed bug in 10.1"  Will PR

**Comment by listingmirror** [comment]
https://github.com/django-money/django-money/pull/223

**Comment by benjaoming** [comment]
Let's keep this issue open just to have some awareness on the incompatibility. @listingmirror thanks for the Readme PR!

**Comment by kissgyorgy** [comment]
@listingmirror you have no idea how much time you saved me! Thank you!

**Comment by rmngrc** [comment]
Have django 1.10.3 and the migrations do not work. More info at #139

**Comment by lorddaedra** [comment]
better to add https://github.com/django-money/django-money/blob/master/setup.py#L56 `,!=1.10.1` here

**Comment by benjaoming** [comment]
Thanks for the feedback! I'm gonna close this -- Django 1.11 is out as an LTS, if there's any problems with it, please do open up new issues!

(also Django 1.10 is dropped from current master branch)
