### ISSUE TITLE
Comparison with different currencies

### ISSUE THREAD

**Issue by ivirabyan** [django-money/django-money#225]
Can you explain why MoneyPatched class doesn't allow equality comparison of two values if they are of different currency? It seems pretty ok to know if `Money(100, 'USD') == Money(100, 'EUR')`.
When you try to do this with MoneyPatched class, you get an error "Cannot add or subtract two Money instances with different currencies". Seems like the message was copypasted from other method, and the error is non relevant here.

**Comment by benjaoming** [comment]
Spot on :)

https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L106

**Comment by ivirabyan** [comment]
Yeah, I saw that line, and it makes me think it was incorrectly copypasted from some other place

**Comment by benjaoming** [comment]
It looks like it indeed :)

But the intention seems okay, I mean not allowing comparison of different currencies. It's better to just fail hard.

**Comment by ivirabyan** [comment]
Comparison in general is really somewhat difficult, but simple equal/non equal is perfectly fine. At least original Money type does that. The purpose of this project is to bring Money type to Django as a model field. Why change it's behaviour?

**Comment by benjaoming** [comment]
> The purpose of this project is to bring Money type to Django as a model field. Why change it's behaviour?

Well, even though it seems accidental, the behavior is already implemented :)

But would be interesting to hear why you would like it to return `False` instead?

**Comment by ivirabyan** [comment]
I simply want to know if the field value changed. Suppose I stored initial field value upon model instantiation, and on save I want to check if it changed.
```
if old_price != self.price:
   # do something
```
That's pretty normal thing to do. At least we must have on option for such behaviour. Right now I had to subclass three classes to just revert to the original behaviour: MoneyField, MoneyFieldProxy, MoneyPatched. It's very overwhelming work to just change one line of code, so I'd like it to be in an original code, at least as an option.

**Comment by benjaoming** [comment]
I'm convinced, thanks :)

**Comment by benjaoming** [comment]
@Stranger6667 any comments? I'm just PR'ing it now...

**Comment by benjaoming** [comment]
PR updated w/ new behavior + release note.

**Comment by ivirabyan** [comment]
Thanks!

**Comment by Stranger6667** [comment]
I agree with @ivirabyan

**Comment by vvkuznetsov** [comment]
> Right now I had to subclass three classes to just revert to the original behaviour: MoneyField, MoneyFieldProxy, MoneyPatched.

As a man who did it, I agree. Thanks for fast change.

**Comment by Stranger6667** [comment]
@ivirabyan 
Should it be closed? Could you check if it works now?

**Comment by ivirabyan** [comment]
Yes, it works now, thank you!

**Comment by Stranger6667** [comment]
👍
