### ISSUE TITLE
__hash__ conflict due to duplicated creation_counter value

### ISSUE THREAD

**Issue by msgre** [django-money/django-money#235]
Hi,
I use https://github.com/jjkester/django-auditlog package in my project and I found, that sometimes `MoneyField` fields are not tracked well (change between old and new state is detected, but only `currency` is saved).
## Investigation

I try to debug what is wrong and found something very internal.

There is function in `auditlog`, which get list of model fields (https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/diff.py#L31). Basically it just call Django's `instance._meta.get_fields()`. Then it make `set` from this list, for example here: https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/diff.py#L80

The problem is, that before `set` I have list like this:

```
[<django.db.models.fields.AutoField: id>, 
<django.db.models.fields.related.ForeignKey: employee>, 
<django.db.models.fields.DateField: date>, 
<djmoney.models.fields.CurrencyField: amount_currency>, 
<django_enumfield.db.fields.EnumField: payment_type>, 
<djmoney.models.fields.MoneyField: amount>]
```

When auditlog put this list into `set`, I get just:

```
{<django_enumfield.db.fields.EnumField: payment_type>, 
<djmoney.models.fields.CurrencyField: amount_currency>, 
<django.db.models.fields.related.ForeignKey: employee>, 
<django.db.models.fields.AutoField: id>, 
<django.db.models.fields.DateField: date>}
```

As you could see, field `<djmoney.models.fields.MoneyField: amount>` is missing. The problem here is, that `<djmoney.models.fields.MoneyField: amount>` **return same hash number** as some other field in my model:

```
(Pdb) out[4]
<django_enumfield.db.fields.EnumField: payment_type>
(Pdb) out[4].__hash__()
264
(Pdb) out[5]
<djmoney.models.fields.MoneyField: amount>
(Pdb) out[5].__hash__()
264
```

(`out` is my temporary list of fields)

To be sure, I print also hashes of other fields:

```
(Pdb) [(i, i.__hash__()) for i in out]
[(<django.db.models.fields.AutoField: id>, -34), 
(<django.db.models.fields.related.ForeignKey: employee>, 261), 
(<django.db.models.fields.DateField: date>, 262), 
(<djmoney.models.fields.CurrencyField: amount_currency>, 263), 
(<django_enumfield.db.fields.EnumField: payment_type>, 264), 
(<djmoney.models.fields.MoneyField: amount>, 264)]
```

So I go deeper in Django internals.

According to https://code.djangoproject.com/wiki/DevModelCreation#InstallingTheAttributes, fields `__init__` call precede `contribute_to_class` (which in case of moneyfield call `add_currency_field` method). So, first all models fields are initialized (and unique `creation_counter` is evaluated) and only then `add_currency_field` is called.

With this knowledge, I think that current implementation of https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L363-L375 is wrong. Particulary this two lines:

```
currency_field.creation_counter = self.creation_counter
self.creation_counter += 1
```

You assign `creation_counter` from `MoneyField` class to `CurrencyField` and then increase `self.creation_counter` **to value that is already attached to another field**. This way, two fields have same `creation_counter` which leads to same `__hash__` used in dicts, sets, etc (see https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/db/models/fields/__init__.py#L473-L474)
## Solution?

```
diff --git a/djmoney/models/fields.py b/djmoney/models/fields.py
index bd315dc..9458fc8 100644
--- a/djmoney/models/fields.py
+++ b/djmoney/models/fields.py
@@ -10,6 +10,7 @@ from django.core.exceptions import ImproperlyConfigured, ValidationError
 from django.db import models
 from django.db.models import F
 from django.db.models.signals import class_prepared
+from django.db.models.fields import Field
 from django.utils import translation

 from djmoney import forms
@@ -309,6 +310,9 @@ class MoneyField(models.DecimalField):

         super(MoneyField, self).__init__(verbose_name, name, max_digits, decimal_places, default=default, **kwargs)

+        self.creation_counter += 1
+        Field.creation_counter += 1
+
     def setup_default(self, default, default_currency, nullable):
         if default is None and not nullable:
             # Backwards compatible fix for non-nullable fields
@@ -369,8 +373,7 @@ class MoneyField(models.DecimalField):
             default=self.default_currency, editable=False,
             choices=self.currency_choices
         )
-        currency_field.creation_counter = self.creation_counter
-        self.creation_counter += 1
+        currency_field.creation_counter = self.creation_counter - 1
         currency_field_name = get_currency_field_name(name)
         cls.add_to_class(currency_field_name, currency_field)
```

I simply move forward `creation_counter` by 2 instead of 1 (first move in `Field.__init__`, second here) and **update global counter** (so next field in model have no conflict with our `MoneyField`. Meaning of this is that I save two values for our field (one for amount, second for currency).

Second modification is in `add_currency_field` method. Instead of accessing next `creation_counter` I use current and previous value (already saved in constructor).

But I am not sure about side effect. For example original `Field` operate also with `auto_creation_order` (https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/db/models/fields/__init__.py#L171-L176) but I really don't know what does it mean.

Please take a look.

Thanks!

**Comment by Stranger6667** [comment]
Hi @msgre !
Could you, please, specify what Python/Django/django-money version you're running?

**Comment by msgre** [comment]
Yes, sorry I forgot to mention:

```
Python 3.5.2 (default, Sep 24 2016, 05:23:05)

>>> django.VERSION
(1, 9, 7, 'final', 0)

>>> djmoney.__version__
'0.10'
```

I installed `django-money` directly from GitHub via `-e git+https://github.com/django-money/django-money#egg=django-money` in `requirements.txt`.

**Comment by Stranger6667** [comment]
@msgre , thank you for the detailed report and proposed changes!
Everything works, the patch is merged to master.

**Comment by msgre** [comment]
You are welcome. Hope it will work as we expect... :)
