### ISSUE TITLE
Blank money field is not allowed

### ISSUE THREAD

**Issue by ghost** [django-money/django-money#245]
Can someone please post all the parameters we can pass for MoneyField. I am using 0.9.1 version and cannot find a comprehensive usage file. I am looking to make money field blank, set default current to USD and remove currency choices.

**Comment by Stranger6667** [comment]
Hello @farhanishaq !
Sorry for the late response! 
I have a couple of questions :)
Is it general form usage question or question about Django admin integration?

As I understand you are looking for form field without currency choices and blank money field, which will save everything with USD currency, right? or it would be ok to display the currency field with single USD option, which will be always selected?

Could you also tell your Django version?

Thank you, BR

**Comment by farhanishaq** [comment]
@Stranger6667 Thank you for getting back to me. 

That'r right. Remove all currencies and keep USD as selected all the time. I would also like to have a NULL field if it is possible. My Django version is 1.10.

**Comment by oliver-zhou** [comment]
also not working for me.
