### ISSUE TITLE
Can't install 0.10.1 when specifying the version explicitly

### ISSUE THREAD

**Issue by georgema1982** [django-money/django-money#253]
When I run the command

`pip install django-money==0.10.1`

I get the following error:

>   Could not find a version that satisfies the requirement django-money==0.10.1 (from versions: )
No distributions matching the version for django-money==0.10.1

**Comment by AndyHoang** [comment]
I just try update with 0.10.1 few hours ago. Its working. Not sure it help...

**Comment by georgema1982** [comment]
Sorry. Turned out it's a pip version issue. Upgraded pip version and problem solved.
