### ISSUE TITLE
`ModelForm` with a `MoneyField` generates deprecation warning 

### ISSUE THREAD

**Issue by spookylukey** [django-money/django-money#262]
This code uses `forms.MoneyField.__init__(currency_choices=...)`:
https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L412

But this code then deprecates that:
https://github.com/django-money/django-money/blob/master/djmoney/forms/fields.py#L35

resulting in a `PendingDeprecationWarning` that can't be fixed by users of the library.

One of them should be fixed, presumably the former.

Thanks!

**Comment by Stranger6667** [comment]
Hi @spookylukey !
Thank you for the report :) 

Hello @benjaoming :) Can we make a new release?
