### ISSUE TITLE
filtering by django-money field

### ISSUE THREAD

**Issue by Guest007** [django-money/django-money#277]
Hi.
I use django-money field with DRF and need to filter by this field. 
Sorting works well. Just include field in ordering_fields list.
But create filter as usual (total = filters.AllLookupsFilter()) make error like this:
djmoney.models.fields.NotSupportedLookup: Lookup 'endswith' is not supported for MoneyField
(lookup can be different from restart to restart).
How I can make filter in right way?

**Comment by Stranger6667** [comment]
Hello @Guest007 !

Could you, please, provide some simple example of how you define your filters and how you use them?
Also, what version of Python, django-money, Django, DRF are you running?

Some preliminary thoughts are, that we should not restrict lookups on our side - Django should rise an exception in such case. So, we'll see :) Probably we will just remove this code

Best regards,

**Comment by Guest007** [comment]
python 3.5.1
django 1.10.4
drf 3.4.7
django-money 0.10.4
models.py
`class TestModel((models.Model):
    name = models.CharField(max_length=20, blank=True, default='')
    total = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, default=0.0)
`
views.py
`import rest_framework_filters as filters
class TestFilter(filters.FilterSet):
    name = filters.AllLookupsFilter()
    #total = filters.AllLookupsFilter()

class TestViewSet(ModelViewSet):
    ordering_fields = ['name', 'total', ]
    filter_class = TestFilter
`
In settings.py:
`    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_filters.backends.DjangoFilterBackend',
        'rest_framework.filters.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),`

It's all simplified for understanding.
sorting by total works well.
filtering by name too.
But when I uncomment total field in TestFilter - I've got something like
`djmoney.models.fields.NotSupportedLookup: Lookup 'contains' is not supported for MoneyField`

How can I make right filter by django-money field?

**Comment by Stranger6667** [comment]
It seems like a bug in ``django-money``, because we have to filter out some lookups from ``MoneyField. class_lookups``. I'll take care about the fix and let you know when it will be ready. I hope, that we'll release it in ``0.11``

**Comment by Guest007** [comment]
I tried to make `total = filters.NumberFilter(lookup_expr=('gt', 'lt', ))` field in FilterSet. It's not make an error, but `?total__lt=5000` not work. All records returned.

**Comment by Stranger6667** [comment]
Hi @Guest007 !
The fix is merged to master now. Could you, please, check with the latest version from trunk?

**Comment by Guest007** [comment]
WOW! 
Thank you! 
Works great!
