### ISSUE TITLE
How to use django-money register_money_field correctly?

### ISSUE THREAD

**Issue by qasimalbaqali** [django-money/django-money#284]
So I don't really get where to put the register_money_field function in my serializer class. Is it suppose to be something like

`price = register_money_field()`?

**Comment by Stranger6667** [comment]
Hello @qasimalbaqali !
This function should be called only once during application startup. For Django < 1.7 you can put it in your root ``urls.py`` for example.

This function doesn't return anything, so you can just call it at the end of the ``urls.py``:

```python
from djmoney.contrib.django_rest_framework import register_money_field

register_money_field()
```

I'll update the documentation to clarify the issue

Thank you for your question :)

**Comment by qasimalbaqali** [comment]
The only way I could serialize the MoneyField with drf is to create a new class

`class MoneyField(serializers.Field):
    """
    MoneyField is not officially supported by Django REST framework
    so a new field serializer class should be implemented
    """
    def to_representation(self, obj):
        return {
            'amount': "%f" % (obj.amount),
            'currency': "%s" % (obj.currency),
        }

    def to_internal_value(self, data):
        return Money(data['amount'], data['currency'])`

and then using it in my Serializer class like so `price = MoneyField()`. I couldn't do it using django-money alone.

**Comment by Stranger6667** [comment]
We have another approach in DRF integration. For example we have the following model & serializer:

```python

class Expenses(models.Model):
    amount = MoneyField(max_digits=10, decimal_places=2)


class Serializer(serializers.ModelSerializer):
    class Meta:
        model = Expenses
        fields = '__all__'
```

And serialization works in the following way:

```python
>>> instance = Expenses.objects.create(amount=Money(10, 'EUR'))
>>> serializer = Serializer(instance=instance)
>>> serializer.data
ReturnDict([
    ('id', 1),
    ('amount_currency', 'EUR'),
    ('amount', '10.000'),
])
```
In other words built-in field serializes only amount part of money instance, currency is serialized automatically by setting ``fields = '__all__'``. It is different from your implementation, which will create a nested structure.

And deserialization works in the same way - it works with money instance, not with nested structure.

If you need nested approach, then we could add some configuration setting for it.

**Comment by Stranger6667** [comment]
I'm closing this issue. Feel free to reopen it if you have more questions to discuss :)
