### ISSUE TITLE
Different Money Choices for different users

### ISSUE THREAD

**Issue by coler-j** [django-money/django-money#286]
Is it possible to pass choices to the widget on a form depending on a queryset, or a list of values?

I want different users to have different currency options depending on their settings. So far I am just seeing options of setting the choices at a global level.

**Comment by Stranger6667** [comment]
Hi @coler-j !
Sorry for the delayed response. You can set choices during form initialization like this:

```python

class MyForm(forms.ModelForm):
    # fields, meta, etc

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['my_money_field'].fields[1].choices = make_choices_for_user(user)
```

And you have to pass user instance to form. Hope, this will help.

Regards
