### ISSUE TITLE
Handling currencies without cents

### ISSUE THREAD

**Issue by kaedroho** [django-money/django-money#289]
The ``MoneyField`` seems to require you to choose a global divisor for all currencies using the ``decimal_places`` keyword argument. But I need to handle currencies that do have cents and others that don't in the same field. For example GBP, USD and EUR have cents but JPY, ZAR and ISK do not.

Is this something that ``MoneyField`` can handle?

**Comment by Stranger6667** [comment]
Hello @kaedroho 

In a sense of storage we're tied to DB here, underlying column could have only one definition for fractional part, e.g. on PostgreSQL - `NUMERIC(14, 2)`, thus the `amount` part will always be stored in one format.

I don't know, if the issue could be solved on some higher level. It depends on the task. 

If the task is to display a money amount, then a good way to go would be implement it on `pymoneyed` side, it is not implemented at the [moment](https://github.com/limist/py-moneyed/blob/master/moneyed/localization.py#L67) (and here is related [PR](https://github.com/limist/py-moneyed/pull/54/files)) and then add support of this feature to `django-money`.

I hope it would be helpful for you :) 
Best regards :cake:

**Comment by Stranger6667** [comment]
I'm closing this issue. Feel free to reopen it if you have more questions to discuss :)
