### ISSUE TITLE
Python and Django support policy looks not secure

### ISSUE THREAD

**Issue by lorddaedra** [django-money/django-money#312]
django-money supports this Django and Python versions:
> Django versions supported: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11
> 
> Python versions supported: 2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6

Supported Django versions (official):
https://www.djangoproject.com/download/ (scroll down to image or table)
Django 1.8 LTS, 1.10, 1.11 LTS

Supported CPython versions:
https://en.wikipedia.org/wiki/CPython (look at History table)
2.7, 3.3, 3.4, 3.5, 3.6

Using unsupported versions may create secure hole in your project. Best support policy for any project - do not support versions of required packages, which are already unsupported by their developers. It will make code clean and prevent of adding secure holes by your product users.

It's good idea to drop support for Python 3.2, Django 1.4, 1.5, 1.6, 1.7, 1.9 and follow this policy in future.

**Comment by lorddaedra** [comment]
Related #304

**Comment by Stranger6667** [comment]
Absolutely agree. Unfortunately, dropping support was done by accident in a minor release. We'll drop it in djmoney 0.12.

A good point, that we can also drop Python 3.2, because the Django team doesn't test Django 1.8 on Python 3.2 since the end of 2016.

Regards

**Comment by benjaoming** [comment]
Yeah, I agree too. There's no point in doing feature and bug release for unsupported versions of Django.

Btw, something to cry about: https://pyup.io/posts/analyzing-django-requirement-files-on-github/

**Comment by Stranger6667** [comment]
Wow, interesting article! Thanks :)

**Comment by Stranger6667** [comment]
I close the issue since support is dropped in the main branch
