### ISSUE TITLE
Consolidate all settings in one place

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#317]
It could be useful to have all settings in a single variable:

project/settings.py
```
DJMONEY = {
    'CURRENCIES': ['USD', 'EUR'],
    'CURRENCY_CHOICES': [('USD', 'USD $'), ('EUR', 'EUR €')],
    'DEFAULT_CURRENCY': 'EUR',
    'CURRENCY_DECIMAL_PLACES': 5,
}
```

@benjaoming , what do you think?

Also, ``CURRENCY_DECIMAL_PLACES`` seems like not a right name in this context. Decimal places are for amount, not for currency. May be rename it to ``DECIMAL_PLACES``?

**Comment by benjaoming** [comment]
> It could be *useful* to have all settings in a single variable:

Can you explain the useful part? Seems like a bunch of deprecating and people having to update their projects.. seems like a lot of work with only a goal of some naming conventions in mind?

**Comment by Stranger6667** [comment]
The only purpose is to create a namespace to avoid a possible settings collision with other applications. I didn't check about other apps, but there could be some. Not a big issue anyway...
