### ISSUE TITLE
Integrate with Satchless

### ISSUE THREAD

**Issue by narnikgamarnikus** [django-money/django-money#329]
I'm already using your application right now, and I want to implement [Satchless](http://docs.satchless.com/en/latest/item.html).
This library uses [python prices](https://github.com/mirumee/prices)

And I would like to ask, maybe someone has already done what I want to do, that is, use Satchless with django-money together. 

If yes, tell me how you did it.

Thanks.

**Comment by Stranger6667** [comment]
Hello @narnikgamarnikus !
We're using another library for ``Money`` implementation - ``py-moneyed``, which is not compatible with the libraries you provided. We have a couple of strict checks for instances of ``Money``, thus it seems like it could not be trivially integrated. If you have some details of how you want to integrate ``djmoney`` with ``prices`` and ``Satchless``, please, let me know and we could discuss it here.

Kind Regards

**Comment by narnikgamarnikus** [comment]
I can try fork satchels and replace their fields `prices` to `py-moneyed`, and cover with tests.

**Comment by benjaoming** [comment]
@narnikgamarnikus I think you should ask `Satchless` to switch to `pymoneyed` and `django-money`. I just looked at `prices` and it comes across as a limited copy of `pymoneyed`... I can't say for sure if it is an actual copy, the code just looks very similar.

I don't think `django-money` should support this.. I think others are making a mistake by not getting in behind `pymoneyed` as *the* money data model for Python.

**Comment by benjaoming** [comment]
Suggesting to close this.

**Comment by Stranger6667** [comment]
Agreed.
