### ISSUE TITLE
Filtering objects with currency conversion on the fly

### ISSUE THREAD

**Issue by jaavii1988** [django-money/django-money#330]
Hi, this is not an issue, it's more a question.. please excuse me in advance if this is not the right place.

I see this example in the documentation:

```
from djmoney.money import Money
account = BankAccount.objects.create(balance=Money(10, 'USD'))
swissAccount = BankAccount.objects.create(balance=Money(10, 'CHF'))
BankAccount.objects.filter(balance__gt=Money(1, 'USD'))
```
Returns the "account" object

What I need is that the **filter** query returns both objects ("account" and "swissAccount"). I'm integrating currency conversion with djmoney_rates. 

I've been fighting with these for a few days.. any help or orientation is very welcome.
Thanks

**Comment by Stranger6667** [comment]
Hm, could you, please, tell more details about your situation? How you suppose to use conversion? some usage examples would be great :)

**Comment by jaavii1988** [comment]
Basically I have a Property model with a Money attribute named "Monthly_Price".
The properties may have different currencies configured in their respective monthly_price attribute. 
I'm implementing a View to filter Max Prices for the properties to be displayed in the frontend based on this monthly_price attribute.

My ideal situation would have been to have this queryset Property.objects.filter(monthly_price__lte<Money(1000, 'USD')) and automatically would check all the properties and apply currency conversion in the fly to their monthly_price attribute **without considering only the ones with the same currency.** (as it works right now).

I just solved this situation by:

1. Defining a DB Function convert_to_usd(amount, currency) which returns the amount converted to currency based on the currency rate defined in djmoney_rates_rate table. 
2. Implementing a custom MoneyManager with a get_queryset function to annotate the monthly_price attribute in USD (my base currency) using the db function convert_to_usd specified in previous point.
3. Filtering in the view the MoneyManager queryset using the annotated field "monthly_price_usd" using the selected max price in the frontend converted to USD. 

I understand all this text may be a confusing, if anyone reading here is interested in more details let me know and will provide. 
Also if anyone understood this and think there's a better solution please let me know.

Thanks! :)

**Comment by Stranger6667** [comment]
Thank you for the information on this interesting topic :)
Lets assume, that we have the following model definition:

```python
class Property(models.Model):
    monthly_price = MoneyField(max_digits=10, decimal_places=2)
```

Also, we have ``Rate`` model from ``djmoney_rates``. From SQL point of view the naive solution would be like:

```SQL
SELECT AP.id
FROM testapp_property AP
LEFT JOIN djmoney_rates_rate R
ON (AP.monthly_price_currency = R.currency)
LEFT JOIN djmoney_rates_ratesource S
ON (R.source_id = S.id)
WHERE  S.base_currency = 'USD' AND R.value * AP.monthly_price < 1000
```

``R.value`` here represents the value, which should be used to get monthly price in base currency. This query is hard to construct with Django's public API, but we can construct something similar with ``extra`` method:

```python
Property.objects.extra(
    where=[
        '''
        (
            SELECT R.value * testapp_property.monthly_price 
            FROM djmoney_rates_rate R 
            LEFT JOIN djmoney_rates_ratesource S
            ON (R.source_id = S.id)
            WHERE S.base_currency = %s AND R.currency = testapp_property.monthly_price_currency
        ) < %s'''
    ],
    params=['USD', 1000]
)
```

Basically, we always know database table name from ``Property._meta.db_table`` and it could be used as a parameter (unfortunately only on Python level, since some db drivers (e.g. SQLite) don't support such parametrization). Thus being said, we can extend MoneyManager (or just create a new manager) to get more general approach to this situation:

part of djmoney/models/managers.py
```python
def money_manager(manager):
    ...

    class MoneyManager(manager.__class__):

        def get_queryset(self, *args, **kwargs):
            ...

        def filter_with_conversion(self, value):
            return self.extra(
                where=[
                '''
                (
                    SELECT R.value * testapp_property.monthly_price 
                    FROM djmoney_rates_rate R 
                    LEFT JOIN djmoney_rates_ratesource S
                    ON (R.source_id = S.id)
                    WHERE S.base_currency = %s AND R.currency = testapp_property.monthly_price_currency
                ) < %s'''
                ],
                params=[value.currency.code, value.amount]
            )
```

**Comment by jaavii1988** [comment]
Thanks again @Stranger6667 , great solution!

**Comment by ayushin** [comment]
Here is a solution without extra 

```
class QuerySet(SoftDeletableQuerySet):
    def display_currency(self, currency):
        return self.annotate(
            value_base_currency=F('value') / Subquery(
                Rate.objects.filter(currency=OuterRef('value_currency')).values('value')[:1])
        ).annotate(
            value_display_currency=F('value_base_currency') * Subquery(
                Rate.objects.filter(currency=currency).values('value')[:1])
        )
```

**Comment by MehdiDRISSIB** [comment]
Hello @ayushin 
Many thank for you answer. 
Please could you provide the full logic ?

I tried with my MoneyField `default_price `:

`
class ConvertedMoneyQuerySet(models.QuerySet):

    def display_currency(self, currency):
        return self.annotate(
            value_base_currency=F('default_price') / Subquery(
                Rate.objects.filter(currency=OuterRef('default_price_currency')).values('value')[:1])
        ).annotate(
            value_display_currency=F('value_base_currency') * Subquery(
                Rate.objects.filter(currency=currency).values('value')[:1])
        )

`

And how to query please ?

ExampleModel.objects.filter() ?
