### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#342]
Hello @benjaoming !
Can we issue a new release?

Kind Regards

**Comment by benjaoming** [comment]
With pleasure -- I'll release the master branch now.

Should I branch into 0.12.x or should we keep master as the 0.12 branch for now? It's easy not to schedule 0.13 before there are PRs that should be kept back from a patch release, if this makes sense?

**Comment by Stranger6667** [comment]
Hm, sounds good! :) Stable branches will help us with maintaining backward compatibility issues

**Comment by benjaoming** [comment]
It's alive! :)

**Comment by benjaoming** [comment]
Also new branch 0.12.x + master is updated.

Great work!

**Comment by Stranger6667** [comment]
Thank you! :)
