### ISSUE TITLE
Repr of djmoney.money.Money rounded down

### ISSUE THREAD

**Issue by evenicoulddoit** [django-money/django-money#366]
Sorry if this has already been brought up, but I couldn't see anything obvious when searching for repr.

Within a console, if I do the following I get confusing results:

```py
In [63]: m
Out[63]: 9 GBP

In [64]: type(m)
Out[64]: djmoney.money.Money

In [65]: vars(m)
Out[65]: 
{'_constructor_args': ((), {'amount': Decimal('9.75'), 'currency': u'GBP'}),
 'amount': Decimal('9.75'),
 'currency': GBP}
```

However, constructing a `moneyed.Money` result produces the following:

```py
In [67]: m2
Out[67]: <Money: 9.75 GBP>

In [68]: vars(m2)
Out[68]: {'amount': Decimal('9.75'), 'currency': GBP}

In [70]: type(m2)
Out[70]: moneyed.classes.Money
```
It seems like the [py-moneyed team took the decision to remove the rounding down in 2015](https://github.com/limist/py-moneyed/pull/67) - is there a reason you've chosen not to? Looking at your implementation would suggest that you copied the code verbatim when constructing your overloaded version. Should I be exclusively using `djmoney.money.Money` over `moneyed.Money`?

**Comment by Stranger6667** [comment]
Hello @evenicoulddoit !
It was added more than 4 years ago in 6c74279421cb0e66fb39e4495e7ff05aa799b9b5 but I never thought about this part. Probably it was copy-pasted from `py-moneyed` as you mentioned. 

Totally agree, that it is confusing behaviour and it should be changed. I'll clean this up.
Thank you for bringing it up.

Note about usage ``djmoney.money.Money`` over ``moneyed.Money``. ``djmoney.money.Money`` allows you making queries with ``F`` objects, use proper localization settings (from your django app) in Django admin and adds escaping in HTML output. Thus being said, I'd recommend to use it whenever you need features, mentioned above.

Kind Regards

**Comment by evenicoulddoit** [comment]
Thanks for getting back so quick, and for the PR - changes look good! (red lines are always nice :D)
