### ISSUE TITLE
BaseMoneyValidator fails to validate falsy ints and Decimals

### ISSUE THREAD

**Issue by 1337** [django-money/django-money#371]
In [the validator code](https://github.com/django-money/django-money/blob/master/djmoney/models/validators.py#L32), any subclass of `BaseMoneyValidator` will short-circuit the validation if the validator was initialised with a falsy integer or or decimal.

Attach a debugger at this code:

    if not limit_value:  # 0 or Decimal('0')
        return

Steps to reproduce:

1. Create a `MoneyField(max_digits=10, decimal_places=2, default_currency='USD')` (copied from example) but with an additional validator, like so:

    ```
    MoneyField(
        max_digits=10, decimal_places=2,
        default_currency='USD',
        validators=[
            MinMoneyValidator(0),
        ]
    )
    ```

1. Make a migration and migrate.
1. Run the server and save any object with that new field with the Money equivalent of `(-1, 'USD')`. Observe that the validator does not raise a `ValidationError`.

This affects the common use case of validating against negative amounts of money.

**Comment by Stranger6667** [comment]
Hello @1337 !
Thank you very much for the report and reproducing steps :) I'll come back to this issue tomorrow and push the fix

Kind regards

**Comment by Stranger6667** [comment]
Wow, when I was typing the reply you pushed the fix :) Cool

**Comment by 1337** [comment]
It's my first time using tox so please check it out! Meanwhile I'll make a PR for it.
