### ISSUE TITLE
MoneyField wont appear in django admin or DRF

### ISSUE THREAD

**Issue by softmarshmallow** [django-money/django-money#377]
simply it wont appear on django admin.
And wont show up on drf page...
Returning  this message

```
Object of type 'MoneyField' is not JSON serializable
--

```

**Comment by Stranger6667** [comment]
Hello @softmarshmallow !

Could you, please, provide a minimal set-up and some guidance to reproduce the issue?
Also, what Python/Django/django-money versions are you using?
