### ISSUE TITLE
How to define zero for universal `Money`?

### ISSUE THREAD

**Issue by elcolie** [django-money/django-money#378]
Hi
I run into very classic problem
It will be more friendly for me to has universal `zero`
Since I will be easily iterate through the list

My workaround would be another `class` for this summation
If anybody here has shortcut please let me know.

```
Money('0') + Money('1', 'EUR')
```

Error:
`TypeError: Cannot add or subtract two Money instances with different currencies.`

**Comment by benjaoming** [comment]
Seems related to #260 

If your summation is going on in Python and not in the database, you should be able to filter the list of currencies to add before adding them together? Why not remove all the 0s before adding them together?

**Comment by elcolie** [comment]
In my case I have to follow this kind of logic
```python
amount = Money('0')
for i in money_llist:
     amount += i.amount
     ...
```
`money_list` will be the single currency anyway. Then I was designed it that way.

>If your summation is going on in Python and not in the database, you should be able to filter the list of currencies to add before adding them together? Why not remove all the 0s before adding them together?


Yes. I do. I use that way to workaround my case. Looking forward to see the feature in #260 
Thank you very much.
