### ISSUE TITLE
Error in using the money_localize in the template.

### ISSUE THREAD

**Issue by marcelodelta** [django-money/django-money#402]
Error in using the money_localize in the template.

sequence item 7: expected str instance, Money found

2.0.4
TypeError
sequence item 7: expected str instance, Money found
/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py in render, line 218
/usr/local/bin/python
3.6.5

----
$ pip install django-money
INSTALLED_APPS = [
   ...,
   'djmoney',
   ...
]

{% load djmoney %}
...
{% money_localize '4.5' 'USD' %}

Am I doing something wrong?

Thank you

**Comment by f213** [comment]
I've made a PR on this. Does #423 fix your issue?
