### ISSUE TITLE
Add django-money-factories to organisation

### ISSUE THREAD

**Issue by ZuluPro** [django-money/django-money#405]
Hello,
I needed to do some tests linked to django-money.
So I created factory.

Unfortunately, the `tests` directory isn't integrated to `djmoney`, so if I put factories in tests, it won't be available for users.
So I you could accept the repository below in your organisation:
https://github.com/ZuluPro/django-money-factories

**Comment by ZuluPro** [comment]
Hello @benjaoming 
I created factories: helpers for django-money's tests
I thought they should be included in django-money's code,
But if I put them with the rest of tests code, it won't be available for third apps.

So there were several solutions:
- Move `tests`` to `djmoney/tests/`
- Create a separated package

I think the 1st one is the best but I here I propose the 2nd.

To answer to your question, my code is actually not needed for `django-money` but factories are really helpful and I plan to do a PR using them.

**Comment by ZuluPro** [comment]
PS:
The project is ready:
- I use with my tests
- I uploaded to pypi

**Comment by benjaoming** [comment]
I understand now, thanks for explaining! I have invited you to the organization, I cannot move your repo myself, only clone it AFAIK.

> Move tests to `djmoney/tests/`

That's not possible, see: https://docs.pytest.org/en/latest/goodpractices.html

**Comment by ZuluPro** [comment]
Thx!
