### ISSUE TITLE
django_money-0.13.3-py2.py3-none-any.whl is broken, no commands directory included

### ISSUE THREAD

**Issue by 77cc33** [django-money/django-money#412]
Hello,

I have in INSTALLED_APPS both apps
```
    'djmoney',
    'djmoney.contrib.exchange',
```
But I don't see update_rates management commands, whenever I can easily update_rates() by calling this function from the code, and it works fine.

Could you say where to look?

Python 3.6.5 Windows 10

**Comment by 77cc33** [comment]
That's strange, as everything works if package installed directly from git

-e git+https://github.com/django-money/django-money@edb7210fb3100c08810df890fc227e4378f49592#egg=django_money

But if I'am installing from pip install django-money I don't have /djmoney/contrib/exchange/management/commands this directory, and as result I don't have manage.py commands (update_rates, clear_rates)

**Comment by Stranger6667** [comment]
Hi @77cc33 !
Thank you for reporting this issue, I'll fix it today. We got to use `find_packages` instead of manual listing

**Comment by benjaoming** [comment]
0.13.4 is released with the fix, thanks @77cc33 !

**Comment by benjaoming** [comment]
Also it doesn't work because there's no `djmoney/__init__.py` file.

This wasn't detected in the previous tox setup because of `usedevelop` which I fixed in #410 @Stranger6667  :)

**Comment by benjaoming** [comment]
Fixed and released 0.13.5 #417

**Comment by 77cc33** [comment]
@benjaoming thanks now management commands work for me

```
[exchange]
    clear_rates
    update_rates
```

**Comment by benjaoming** [comment]
Thanks for verifying @77cc33 :)
