### ISSUE TITLE
Sprint ideas

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#420]
Hi @benjaoming !

I'd lead a sprint on django-money this weekend and if you have any ideas for the project it would be very nice to discuss them :)

My current ideas (besides existing issues / PRs):

- History for exchange rates
- More providers?
- Jinja2 tag equivalent
- Dropping Django 1.8 support

Best Regards

**Comment by benjaoming** [comment]
Wow, that's super cool @Stranger6667 

Well, I would just add that it would be nice to conclude the two open PRs! I have held off with releasing 0.14 until now, seeing if we could get #261  in ..

Feel free to branch off `master` to `0.14.x` if you want to target any of the new work for `0.15.x`.

**Comment by benjaoming** [comment]
Congrats on your sprint! :) I am going to close this now -- `master` has been released with your changes, and is tracking the 0.14 series.

**Comment by Stranger6667** [comment]
Thanks! :heart:

**Comment by Stranger6667** [comment]
The most notable outcome of the sprint was a very valuable feedback on our documentation from one of the most skilled professional tech writers I know - [Mikey Ariel](https://twitter.com/thatdocslady) from Red Hat

I'll submit the feedback in a next few weeks probably (currently I'm quite limited in time)

**Comment by benjaoming** [comment]
@Stranger6667 that's amazing, I was just thinking that this little Django app here has a lot of best-practice 'ish nurturing. Just that the documentation is the only remaining weak spot.
