### ISSUE TITLE
Wrong get_rate results if base currency is not USD

### ISSUE THREAD

**Issue by 77cc33** [django-money/django-money#425]
Hello, 

openexchangerates FREE accounts return only USD base currencies, so if we have EUR base currency

![image](https://user-images.githubusercontent.com/2612157/41357807-a526f1dc-6f2f-11e8-9ffc-a586c54c47a8.png)

rates table will include USD rates anyway

![image](https://user-images.githubusercontent.com/2612157/41357908-e020d884-6f2f-11e8-80a6-08d17aa50994.png)

![image](https://user-images.githubusercontent.com/2612157/41357882-d32e377a-6f2f-11e8-9158-b2b4b3b52908.png)

Maybe during rates_update we can check this situation and recalculate rates accordingly to base currency set in django app?

**Comment by 77cc33** [comment]
by the way, right now I'am using this code for exchange directions what are not supported, maybe it's worth to add into your lib? 

```
def convert_currency(amount, from_cur, to_cur):
    return amount * get_rate(from_cur, 'USD') / get_rate(to_cur, 'USD')


print(
    convert_currency(amount=10, from_cur='GBP', to_cur='AUD')
)

**Comment by Stranger6667** [comment]
Hi!
I thought, if `base` will be `EUR`, then openexchangerates will rise an error. Or do you mean if we manually change base currency?

**Comment by Stranger6667** [comment]
About non-direct conversion - I missed this feature, thanks for spotting it :) I'll add it

**Comment by 77cc33** [comment]
@Stranger6667 if base is EUR, openexchange doesn't rise an error for me, but just saves USD rates with "EUR" as base currency in database as shown above.

**Comment by Stranger6667** [comment]
Ok, we'll merge this conversion feature soon, and then I'll look at this issue with base currency

**Comment by Stranger6667** [comment]
I tried to change `base` to `EUR` and got this response:


```
{
  "error": true,
  "status": 403,
  "message": "not_allowed",
  "description": "Changing the API `base` currency is available for Developer, Enterprise and Unlimited plan clients. Please upgrade, or contact support@openexchangerates.org with any questions."
}
```

Unfortunately, `ExchangeBackend.base_currency` is ignored when the rates are updated, only `settings.BASE_CURRENCY` is used and if it is set to `EUR` on a free account, then an error will rise.

A possible strategy could be retrying getting the rates with `base=USD` and converting them to the desired currency, however, I'm not sure if we can detect this error in all cases + this is also a backend-specific. Checking the description message is quite shakey - we can easily miss the case if it will be changed on their side.

**Comment by Stranger6667** [comment]
Feel free to reopen the issue if any issue still occurs
