### ISSUE TITLE
Comparison failing after doing arithmetic.

### ISSUE THREAD

**Issue by KaiserKarel** [django-money/django-money#426]
After multiplying a moneyfield with a decimal.Decimal, comparisons fail.

Example:

```python
def test_dj_money_Money(self):
        from djmoney.money import Money
        import decimal
        initial = Money(100, "EUR")
        final = initial * 0.9
        # This test does pass.
        self.assertTrue(initial * 0.9 == final)

        final = initial * decimal.Decimal(0.9)
        self.assertTrue(initial * 0.9 == final, msg="initial * 0.9: {}, final: {}".format(initial * 0.9, final))
```
Results in:
```commandline
AssertionError: False is not true : initial: 90.00 EUR, final: 90.00 EUR
```

**Comment by Stranger6667** [comment]
Hi @KaiserKarel !

When you're multiplying `initial` by `float` value, it is converted into string [here](https://github.com/limist/py-moneyed/blob/master/moneyed/classes.py#L143) and then into Decimal. But when you're multiplying it by `Decimal` constructed from `float` it is not exactly `0.9`:

```
>>> decimal.Decimal(0.9)  # In your test
Decimal('0.90000000000000002220446049250313080847263336181640625')
>>> decimal.Decimal('0.9')  # This is a conversion result of float value `0.9` in `py-moneyed`
Decimal('0.9')
```

This behavior is documented [here](https://docs.python.org/3/library/decimal.html#decimal-objects)  (there is a paragraph that describes `Decimal` behavior when `float` is passed).

Also, there is a [warning](https://github.com/limist/py-moneyed/blob/master/moneyed/classes.py#L141), that multiplying by `float` values is deprecated and I think it should be removed to be in line with default Python behavior for such cases:

```
>>> decimal.Decimal('0.9') * 0.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'Decimal' and 'float'
```

But this issue should be addressed in `py-moneyed` though.

**Comment by KaiserKarel** [comment]
Thanks for the clarification! Seems to me that multiplying by floats should indeed be removed. I reckon I did not see the warning because the django testrunner redirects stdout adn stderr.

**Comment by benjaoming** [comment]
Thanks for the explanation @Stranger6667 !

And yes, @KaiserKarel - if you are doing tests, it is actually cool that such errors are caught. You money-handling system has to be deliberately handling all sorts of decimals, floating points aren't suited because you aren't fully in control, while Decimal types offer you the deliberate control of how many decimals are relevant.

Closing this, good luck :)
