### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by lggwettmann** [django-money/django-money#429]
Hey guys,

I'd like to make it possible for users to only choose specific amounts eg '100 €', '200 €', '300 €' in a form field. I tried to change the MoneyField with another widget, but MoneyField does not seem to accept a widget. How can I solve this?

```
class SomeForm(Form):
    money = models.MoneyField(widget=forms.Select, choices=TOPUP_OPTIONS)
```

**Comment by ZuluPro** [comment]
The MoneyField you are using is a DB field (for models). For forms, you must use a Form field which are in `django.forms`.

**Comment by benjaoming** [comment]
What @ZuluPro said :)

Closing this
