### ISSUE TITLE
Decimal object has no attribute amount

### ISSUE THREAD

**Issue by milutinke-kortechs** [django-money/django-money#430]
Hi,

In `migrations` files for exaple next code is present:
`other_cost = MoneyField(max_digits=16, decimal_places=2, default_currency="EUR", null=True, blank=True)`

When I try to apply this migration, I got this errror:

`File` "....env/lib/python2.7/site-packages/djmoney/models/fields.py", line 296, in deconstruct
    kwargs['default'] = self.default.amount`

`self.default` is type `Decimal` and because of that `amount` property doesn't exists in `desconstruct` method.

I think `set_default` method returns proper `default` value, but that value isn't set up in `self.default` to override `self.default` from `super` class (`DecimalField`).

Is my code wrong or this is a real issue?

**Comment by Stranger6667** [comment]
Hi @milutinke-kortechs !

I need to check if the migration is generated correctly for this case. I'll get back to you when the test case will be ready

**Comment by milutinke-kortechs** [comment]
Hi @Stranger6667 
I must tell You that this migrations (and similar) are done year ago. 
I read somewhere here in some issue, that `django-money` in some earlier versions `default=Decimal(0.0)` was default behavior.

Maybe be that that caused the problem? Maybe newer version aren't backward compatible?!

Thanks!

**Comment by milutinke-kortechs** [comment]
Hi @Stranger6667 

We resolved this by updating on newest version of `django-money`!

Thanks! :)

**Comment by benjaoming** [comment]
Hi @milutinke-kortechs 

Thanks for reporting and following up!

> We resolved this by updating on newest version of django-money!

Just want to make sure: You meant that this was solved by _updating **to** the newest version_?

If this is the case, I would dare close this issue :)

**Comment by milutinke-kortechs** [comment]
I think, yes. 
Because in our version, `super` method was called before `setup_default`. And Thatn `DecimalField` didn't get proper default value that you used in `deconstruct`.

No problem! 
Thanks
