### ISSUE TITLE
Converting MoneyField back to original value

### ISSUE THREAD

**Issue by saranshbansal** [django-money/django-money#431]
How do I convert a MoneyField value back to the original form?
I have a modal field:
```
client_cost = MoneyField(
        _('client cost'),
        max_digits=10,
        decimal_places=2,
        default_currency='AUD',
        null=True,
    )
```
Now i want to do some calculations on it so i converted it to int using `int(client_cost) `
However I'm getting an error (obviously):

`int() argument must be a string, a bytes-like object or a number, not 'Money'
`

Please help.

**Comment by Stranger6667** [comment]
Hi! Use ‘int(client_cost.amount)’
