### ISSUE TITLE
Plan for 0.15

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#436]
Hi @benjaoming !
What do you think about making a new release? I was thinking, that we could deliver a new feature and a bugfix, since last 2 weeks there were not really many changes

Cheers

**Comment by benjaoming** [comment]
Sounds good, I'm available :)

You're welcome to ask anything - no problem bumping to 0.15, neither!

**Comment by Stranger6667** [comment]
Initially, I thought about just issuing a new release just now :) Not like planning, but anyway we could plan something :) 

For example for the next release it could be:
- Dropping Django 1.8
- #411 
- #434 
- Finishing a part of #425

**Comment by ZuluPro** [comment]
@Stranger6667 @benjaoming Could we pass the tests from pytests to Django ?

**Comment by Stranger6667** [comment]
@ZuluPro What do you mean?

**Comment by ZuluPro** [comment]
Hello @Stranger6667,
Sorry for my latency,

Actually for tests we're using pytest, which is a great tool.
But Django has its own unit test framework and it's more adapted and easier to use.
I know it's a huge job, but I ask.

**Comment by Stranger6667** [comment]
In this case, I'd love to hear about concrete benefits, that could be achieved by migrating the test suite to Django's testing framework. I have a couple of questions about that.

- What kind of tasks / tests could benefit from switching?
- In what way is it better adapted? pytest-django is using a lot of features of Django's testing utils under the hood and they are used there.
- Are there any replacements for used pytest features? Reusable fixtures, parametrization, function-based tests, plain assert usage

Also in Django's test framework, `assert*` methods are used, that are quite more verbose and I'm not sure if we need any of them in our test suite.

I concerned, that spending a tremendous amount of efforts on switching to another testing framework will pay off in any way like having simpler tests, lower entry barrier or faster development. To make some consideration I need more reasoning about that idea.

I'd say if we need some features of Django's test framework, then we could use adapt them and use with existing test suite setup, it will be much simpler

**Comment by benjaoming** [comment]
IMO it's okay to mix pytest and `django.test.TestCase`, as long as it doesn't affect DRY too negatively. They can co-exist. It's still possible to invoke everything with `pytest`.

I prefer pytest's simple functions and pattern for fixtures etc. But I understand if someone things `TestCase` is easier to inherit from.

It becomes a bit like functional views vs. class-based views :)

**Comment by benjaoming** [comment]
> I'm voluntary to make this job alone and propose a big PR ;)

@ZuluPro that's great - I wouldn't like if the pytest invocation disappeared (because it has concise output and log handling), but other than that, just go ahead.

I'm not really convinced of any benefits, but maybe if I saw it in a PR, I would understand it better.

>  I think (real) fixtures are bad: difficult to maintain, I really prefer factories (from factory boy),

That's a dangerous idea. Real fixtures are often closer to real usage. When they need maintenance, that's often for a good reason and highlights backwards incompatibilities.

Factories and their dependencies are more complex set up and hard to understand the scope of (what cases they are set up to cover). It adds automation, but the cost is the added complexity.

In this particular project, we have the case of money, currencies, custom managers, arithmetics etc.. so the automation probably has to be combined with hard-coded fixtures.

Btw our greatest tests are still coming from people reporting issues about things we didn't know about nor anticipate :)

**Comment by Stranger6667** [comment]
> As Django's default TestCase uses transactions all tests with DB could be speed up

pytest-django uses it as well in `db` fixture. `TransactionalTestCase` logic is used in `transactional_db` fixture. Thus being said, there will be no performance difference regarding DB queries.
Relevant implementation is here - https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/fixtures.py#L121

> I think (real) fixtures are bad: difficult to maintain, I really prefer factories (from factory boy),

Fixtures are a great example of the dependency injection pattern, which idea is to separate implementation and simplify testing. Also, fixtures in pytest are not only about objects creation. They are flexible in the way that you could use factory boy factory, some custom generator, basically, anything and you're not forced to choose some exact approach. You could call factory boy factories in it or create some complicated setup and then reuse it or parametrize. In what way is it difficult to maintain? Have you tried `pytest-factoryboy`?

> Reusable fixtures and parametrization are mock out, it could be done with a decorator from `mock.patch`

Could you provide a link to the decorator you mentioned? Would it yield different test cases when applied to a test? Would it provide some caching for expensive set-ups?

> plain assert usage: Yup of course

Does it provide an extended introspection as pytest does?

> But in practice, it's a bit hard deal with a mix of django.test and pytest. Too much question just to create some test:

I don't think, that these questions are recurring, it is more like that they will be solved after reading pytest documentation. More important questions are about testing logic and quality of the result of writing a test. It is just an instrument to make things. When you know how to use it - you will not have questions like this.

> I think pytest is a good tool as launcher, but as library, it doesn't provide any particular thing in a Django app (compared to Django+StdLib)

Django has a lot of really cool testing tools - it would be nice to have more assertions from the test cases (https://github.com/pytest-dev/pytest-django/pull/232). But pytest itself has quite a lot, as I mentioned before (parametrization on all python versions, fixtures (including generator-based + autouse feature)), but the most important is the flexibility it has - you can write function-based tests or use a default Python's `unittest`, or from Django. In general, the tests could be cleaner, since you just type less. 

I don't want to write about all this stuff here, but it definitely worth checking - https://docs.pytest.org/en/latest/contents.html

> I'm voluntary to make this job alone and propose a big PR ;)

I doubt that it will ever be merged. Because the motivation is not objective and is a matter of personal taste. More likely it will reduce the flexibility we have there without any valuable benefit. At least I don't see any now. If you'll provide some examples of how the test suite will be better and why - it would be a good starting point for the discussion. Let's start with a concrete, incremental changes with concrete benefits instead of a single big pull request. For example - factory boy could be helpful in our test suite, for sure, but it needs to be checked.

From my perspective it is not a big priority at the moment, I think there are a couple of things in our issues list that could be done much easier and add more benefit (it is more clear at least) to the end user.

Cheers

**Comment by benjaoming** [comment]
I think I agree mostly with @Stranger6667 - but I think tests in general should and can be mixed from both worlds. In larger projects, you often have to accept that sometimes factories are better than fixtures and vice versa.

My personal preference for tests is that they are easy to maintain and understand when they break. Because often someone who didn't write a particular test has to be able to quickly understand why it broke. Too much magic and complex DRY patterns can make that more consuming than the benefit that a bit of DRY can add in the initial authoring phases.

Maybe, @ZuluPro if you are not too turned off by our skepticism, you can start by improving exactly those tests that you believe can benefit from a new pattern?

**Comment by Stranger6667** [comment]
@benjaoming I also think, that they could be mixed. If something is making the code better in a certain way - let's use it. E.g., all these Django's asserts, that don't have equivalent in pytest. In our case we don't need a lot of them - for example, all asserts for request/response because we work on a lower level with models and fields.
