### ISSUE TITLE
Add two MoneyFields in different currencies and generate output in given currency

### ISSUE THREAD

**Issue by saranshbansal** [django-money/django-money#438]
Hi I've been scratching my head over past few days to figure out how to manipulate dj-money fields.
Here are my two model fields: 
```
 client_cost = MoneyField(
        _('client cost'),
        max_digits=10,
        decimal_places=2,
        default_currency='AUD',
        null=True,
    )
```

```
camera_operator_cost = MoneyField(
        _('camera operator cost'),
        max_digits=10,
        decimal_places=2,
        default_currency='AUD',
        null=True,
    )
```

They can have completely different currencies (default being 'AUD'). 
I need to be able to: 
- extract currency from these fields. (Need the exact statement).
- add these two fields which could have amounts in any currency.  
- reformat the total in whatever currency I want. Let's say total in AU$ is 250 and now i want the same value in US$ which will be ~184US$

Please help.

**Comment by benjaoming** [comment]
I think you're asking a bit much here TBH.

We are developing the library :) It has what you need to convert between different currencies. But that nitty-gritty logic to add together random currencies and how you want this conversion done exactly: That's you head ache unfortunately :)

Latest release has the option to convert between different currencies using an intermediate currency (typically USD). See: http://django-money.readthedocs.io/en/stable/changes.html#added
