### ISSUE TITLE
Can't update exchange rates

### ISSUE THREAD

**Issue by saranshbansal** [django-money/django-money#441]
I added these three lines in my settings.py file(after adding `'djmoney'` and  `'djmoney.contrib.exchange',
` to installed apps and running the migrate command.

OPEN_EXCHANGE_RATES_APP_ID = 'https://openexchangerates.org/'
OPEN_EXCHANGE_RATES_URL = 'https://openexchangerates.org/api/latest.json'
BASE_CURRENCY = 'AUD'

when i use convert_money, it says:
`    raise MissingRate('Rate %s -> %s does not exist' % (source, target))
`
Also, I can't run `python manage.py update_rates
`
it says unknown command 'update_rates'

Please help.
versions:
Python 3.6
Django 2.0.3
djmoney 0.13.2

**Comment by Stranger6667** [comment]
Hi!

Could you specify what are the versions of Python, Django, djmoney are you running? 

At first glance OPEN_EXCHANGE_RATES_APP_ID is not valid since it contains an url

**Comment by Stranger6667** [comment]
Basically the first thing you have to do is to update rates, and only after that use conversion. Btw, have you add djmoney to INSTALLED_APPS as well?

**Comment by saranshbansal** [comment]
@Stranger6667 
updated description for versions.
In the docs it was written:

> If you want to implement your own backend, you need to extend djmoney.contrib.exchange.backends.base.BaseExchangeBackend. Two data sources mentioned above are not open, so you have to specify access keys in order to use them:

```
OPEN_EXCHANGE_RATES_APP_ID - https://openexchangerates.org/

FIXER_ACCESS_KEY - https://fixer.io/
```

Also, python manage.py update_rates says unknown command.

**Comment by saranshbansal** [comment]
> At first glance OPEN_EXCHANGE_RATES_APP_ID is not valid since it contains an url

Oh I see, so first i need to generate an app_id from that site. That's a bummer. It's chargeable and i can't use the free account for production.

**Comment by Stranger6667** [comment]
I'll fix the doc :)

Could you, please, update to the latest djmoney version and try to run the command again?

**Comment by Stranger6667** [comment]
Now we have:

```
Two data sources mentioned above are not open, so you have to specify access keys in order to use them:

``OPEN_EXCHANGE_RATES_APP_ID`` - '<your actual key from openexchangerates.org>'

``FIXER_ACCESS_KEY`` - '<your actual key from fixer.io>'
```
