### ISSUE TITLE
How to specify currency value?

### ISSUE THREAD

**Issue by cryptobench** [django-money/django-money#447]
Let's say I have my own currency that's worth 780 and compare it to the danish crown DKK , so 1 DKK equals 780 of my currency

The current documentation shows this , but I have no clue how to specify it's value based on this. Care to elaborate? 

```
import moneyed
from moneyed.localization import _FORMATTER
from decimal import ROUND_HALF_EVEN


BOB = moneyed.add_currency(
    code='BOB',
    numeric='068',
    name='Peso boliviano',
    countries=('BOLIVIA', )
)

# Currency Formatter will output 2.000,00 Bs.
_FORMATTER.add_sign_definition(
    'default',
    BOB,
    prefix=u'Bs. '
)

_FORMATTER.add_formatting_definition(
    'es_BO',
    group_size=3, group_separator=".", decimal_point=",",
    positive_sign="",  trailing_positive_sign="",
    negative_sign="-", trailing_negative_sign="",
    rounding_method=ROUND_HALF_EVEN
)
```

**Comment by Stranger6667** [comment]
Hej @cryptobench !

Sorry for not getting back to you for so long :(

The docs you mentioned are only about string representation of your currency, the relative value of the currency could be specified via exchange rates - https://github.com/django-money/django-money#working-with-exchange-rates

However, it depends on your use case. Hopefully, exchange rates will solve your issue (if it is relevant after this long time)

Feel free to reopen if you have any further questions

Cheers :)
