### ISSUE TITLE
Cannot get Travis tests to pass on empty commit

### ISSUE THREAD

**Issue by GeeWee** [django-money/django-money#451]
See #450 - if I make a PR with an empty commit, I cannot get Travis to pass the tests. Last time the master branch was built (4 months ago) it passed fine. I'm not sure what's going on here.

I'd really like to contribute to this project, and if I'm doing something wrong, I'll volunteer to update the contribution docs.

**Comment by Stranger6667** [comment]
I suppose that it is connected with the new `py-moneyed` release - `0.8.0`.

I'll try to handle these changes this week. But please, feel free to propose your changes, even if some tests are failing - I'll review them :)

Thank you

**Comment by GeeWee** [comment]
I think I'd prefer to start fixing things once I have a grasp of what breaks things and what doesn't. New codebases can be scary ;)
I'd love it if you had time to take a look at it.

**Comment by Stranger6667** [comment]
The issue should be fixed now :)
