### ISSUE TITLE
Unexpected type when using values on query?

### ISSUE THREAD

**Issue by xliiv** [django-money/django-money#460]
I noticed unexpected (IMO) behaviour when using `Django's` [values](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#values)

Let's say i have this model
```python
# models.py
class MyModel(models.Model):
    price = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency=settings.PAYMENT_DEFAULT_CURRENCY,
    )
```
When querying object i'm getting
```
ipdb> type(models.MyModel.objects.first().price)                                                                                         
<class 'djmoney.money.Money'>
```
which is what i expect, `Money` model. However when i'm doing this
```
ipdb> type(models.MyModel.objects.values('price').first()['price'])                                                                      
<class 'decimal.Decimal'>
```
it's `Decimal`.

Is this is intentional? How can get `Money` when using `values`?

Thanks

**Comment by Stranger6667** [comment]
Hej @xliiv
Interesting issue :) we don’t support returning ‘Money’ instances in ‘values’ or ‘values_list’ methods at the moment. However it could be a nice feature

**Comment by xliiv** [comment]
This makes sense, since under the hood `django-money` splits `money` to 2 database fields
* price
* price_currency

Anyway thanks for quick resposne :)
