### ISSUE TITLE
Graphene / GraphQL support?

### ISSUE THREAD

**Issue by gotexis** [django-money/django-money#468]
Aside from the DRF support, I wonder if there is any Graphene support or it should just work?

**Comment by Stranger6667** [comment]
Hello @gotexis !

I didn't try this, and I'm not aware of how `graphene` works with Django :) Would be nice to know if there are any issues with it, but I can't provide any feedback at the moment :(

**Comment by Stranger6667** [comment]
Feel free to reopen if there will be any issues with Graphene support :)
