### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by kmartynski** [django-money/django-money#489]
Hi, I've tried to use your library, but I got this error. I guess it is common now, because after new Django upgrade, when having relation fields, you have to add `on_delete` field.

**Comment by washeck** [comment]
Can you please post the code of your model?

**Comment by kmartynski** [comment]
There is no code, because an error occurs when I add `django-money` to `INSTALLED APPS` in settings.py

**Comment by benjaoming** [comment]
@kmartynski it sounds like you have an error somewhere else in your project. This project doesn't have models, so doesn't have any foreign keys that would require `on_delete`.
