### ISSUE TITLE
Currency exchange

### ISSUE THREAD

**Issue by kmartynski** [django-money/django-money#493]
Hello, I wanted to implement small function, which will show a converstion rate of specific currencies. I updated my `INSTALLED_APPS` `'djmoney.contrib.exchange'`. I wrote this simple code, but I got an error: `djmoney.contrib.exchange.exceptions.MissingRate: Rate EUR -> USD does not exist`

code:
`from djmoney.money import Money
from djmoney.contrib.exchange.models import convert_money
convert_money(Money(100, 'EUR'), 'USD')`

In `settings.py` I've also included stuff like:
`EXCHANGE_BACKEND = 'djmoney.contrib.exchange.backends.FixerBackend'
CURRENCIES = ('USD', 'PLN', 'EUR', 'CHF', 'RON', 'GBP')
BASE_CURRENCY = "PLN"`

**Comment by benjaoming** [comment]
You need to update your local rates, see the docs: https://github.com/django-money/django-money#working-with-exchange-rates

**Comment by kmartynski** [comment]
Well, the only thing this documentation says is to use `pip install "djmoney[exchange]"`, which gives me this error: `Could not find a version that satisfies the requirement djmoney[exchange] (from versions: )`. So it is quite unintuitive. I've installed manually this `certifi` library, but it also doesn't change anything. Using commands `python manage.py update_rates` doesn't work as well.

**Comment by benjaoming** [comment]
That was a clear mistake! Should be `pip install "django-money[exchange]"`

**Comment by kmartynski** [comment]
Why do you close this thread, when the problem still occurs? I used new command, but after I still got the same error. Can you explain in one message, how to implement all of this? Documentation doesn't help at all in this matter.

**Comment by washeck** [comment]
@kmartynski What exactly is failing at the moment? 
When you run
`$ python manage.py update_rates`
do you see
`Successfully updated rates from openexchangerates.org`
message?

**Comment by kmartynski** [comment]
`django.core.exceptions.ImproperlyConfigured: settings.FIXER_ACCESS_KEY should be set to use FixerBackend`
So I set my own key, which I got from `https://openexchangerates.org/`, but now I get 
`    return self.parse_json(response)['rates']
KeyError: 'rates'`

**Comment by kmartynski** [comment]
Ok I was managed to solve it. CLOSED

**Comment by benjaoming** [comment]
> Why do you close this thread, when the problem still occurs?

@kmartynski you are always welcome to open an issue about a bug or feature request. But otherwise, we have described support steps here: https://github.com/django-money/django-money/blob/master/.github/SUPPORT.rst
