### ISSUE TITLE
Release 0.15?

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#496]
Hej @benjaoming !

What do you think about making a new release? 

We have quite a lot of changes now and we didn't remove support for old Django versions (1.8 & 2.0) yet. Would it make sense to have 0.15.x branch as the last to support these versions? and then continue with Dropping 1.8 & 2.0 + making some more refactorings with possible backward-incompatible changes

**Comment by benjaoming** [comment]
I think it sounds good :ship: :fireworks:

**Comment by Stranger6667** [comment]
Great! 🍰 🎉

**Comment by joshua-s** [comment]
The DRF field fix in this is especially important.

**Comment by benjaoming** [comment]
0.15 is now released and tracked in branch `0.15.x`. The current `master` branch is set to track the next `1.0` release.
