### ISSUE TITLE
Tox env for pypy2.7 is misconfigured thus tests fail

### ISSUE THREAD

**Issue by atleta** [django-money/django-money#511]
I did a small fix and created a pull request but the tests failed (see https://travis-ci.org/django-money/django-money/jobs/588676965 ), because one of the tox envs (pypy2.7-5.8.0) is misconfigured. It tries to pull this file, which is not there: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/pypy2.7-5.8.0.tar.bz2

**Comment by benjaoming** [comment]
This was fixed in https://github.com/django-money/django-money/pull/517
