### ISSUE TITLE
Converting money instance table for rest framework to user default currency 

### ISSUE THREAD

**Issue by kimutaiRop** [django-money/django-money#512]
I have a table that has the money instance and different users can always choose the currency they want to use, I was wondering if there is a way that the money field amount can always be sent to a user with the currency he/she wishes to see,

**Comment by benjaoming** [comment]
Dear @kimutaiRop - glad that you are using the project!

I can't really understand the question, so I'm not sure what to answer. There is documentation about it all here, so I hope that can help you: https://django-money.readthedocs.io/en/latest/

For general support inquiries, we ask people to kindly not post issues, as this is a reserved space for features and bug reports.

Thanks,
B
