### ISSUE TITLE
Add Django 3 support, remove Python 2.7 support

### ISSUE THREAD

**Issue by Hispar** [django-money/django-money#514]
Better to add `six` as a dependency for compatibility.

https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by benjaoming** [comment]
Thanks for reporting @Hispar - I would propose that we remove Python 2.7 support entirely, so we don't complicate the app any further.

People depending on 2.7 can use older releases.

@Stranger6667 does this sound like an okay plan for a 0.16 release?

**Comment by Stranger6667** [comment]
It sounds great :)

**Comment by benjaoming** [comment]
Just correcting myself here: The next release is not 0.16, but in fact the 1.0 we have been talking about for so long :)

**Comment by benjaoming** [comment]
Fixed in #515

@Stranger6667 looking at the 1.0 milestone, we have just 1 issue open: https://github.com/django-money/django-money/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0
