### ISSUE TITLE
Way to stop currency choice being shown

### ISSUE THREAD

**Issue by RaddishIoW** [django-money/django-money#538]
Is there a way to stop the currency choices input being shown if there is only one allowed currency? I don't need to display this input on my form, but I can't seem to find a way to prevent it being shown.

**Comment by benjaoming** [comment]
Hi @RaddishIoW 

You can read the definition of MoneyField used in forms here: https://github.com/django-money/django-money/blob/master/djmoney/forms/fields.py

Then you can assign your own widget like this for instance:

```
class MyForm(forms.Form):
    my_field = MoneyField(currency_widget=forms.HiddenInput())
```

Please do not use our Github issue tracker for support requests: https://github.com/django-money/django-money/blob/master/.github/SUPPORT.rst
