### ISSUE TITLE
Object of type Money is not JSON serializable when define natural key method for related model with MoneyField

### ISSUE THREAD

**Issue by makmary170** [django-money/django-money#540]
Hello, i have this problem:

I have two models, one of them have MoneyField, the other have FK to it.
When i define method `natural_key` for related model with MoneyField for fixtures i have the error:
`CommandError: Unable to serialize database: Object of type Money is not JSON serializable`

The example of the models is bellow:

```
from django.db import models
from djmoney.models.fields import MoneyField


class A(models.Model):
    summary = MoneyField(max_digits=14, decimal_places=2)

    def natural_key(self):
        return (self.summary,)


class B(models.Model):
    name = models.CharField(max_length=50)
    a_ref = models.ForeignKey(A, on_delete=models.CASCADE)

    def natural_key(self):
        return (self.name,) + self.a_ref.natural_key()
    natural_key.dependencies = ['test_app.a']
```

**Comment by washeck** [comment]
Money object is not JSON serializable. If you absolutely need this you can use `str(self.summary.amount)` and `self.summary.currency` to construct the natural key. But I don't understand why would you use the `summary` value as natural key. Can you explain what are you trying to achieve?

**Comment by makmary170** [comment]
I do this because MoneyField value is a part of natural key. For example I have several transactions with specific created and amount in fixtures and if this already in my database I don't want to duplicate this after fixtures reloading.

**Comment by benjaoming** [comment]
See: https://github.com/django-money/django-money#usage-with-django-rest-framework
