### ISSUE TITLE
How would I set up a UniqueConstraint for a MoneyField?

### ISSUE THREAD

**Issue by lggwettmann** [django-money/django-money#543]
Hey guys,

if I set the MoneyField as unique or set up a UniqueConstraint for it, Django only regards the amount, but not the currency. So USD 10 and EUR 10 are seen as the same even though they should not be.

How would I go about fixing this?

Kind Regards

**Comment by benjaoming** [comment]
Hi @lggwettmann - can you potentially solve this with `unique_together` on your models Meta class?

For instance:

```
class Blah(models.Model):
    money = MoneyField(...)
    class Meta:
        unique_together = ("money", "money_currency")
```

Am not sure if the auto-added `money_currency` is a valid choice.

**Comment by lggwettmann** [comment]
Awesome! Thanks, that did the trick. 

I had tried this which didn't work but I didn't try it without _amount. 
```
constraints = [
            models.UniqueConstraint(
                fields=['operator', 'by_receipt_total_amount', 'by_receipt_total_currency'],
                name='unique_amount_and_currency_for_operator'
            )
        ]
```

Thank you!
