### ISSUE TITLE
Money Field in SQLite and PostgreSQL

### ISSUE THREAD

**Issue by aladinbenz** [django-money/django-money#548]
Hello,
I'm using Django-money to track changes history of money field in both templates and admin.
When using Django-money in dev with SQLite everything seems to work just fine.
**TEMPLATE:**
<img width="537" alt="template" src="https://user-images.githubusercontent.com/56277363/80897667-85576a80-8cfb-11ea-9b54-5707bf2b54e7.png">
**ADMIN:**
<img width="188" alt="admin" src="https://user-images.githubusercontent.com/56277363/80897672-92745980-8cfb-11ea-9041-86140e759444.png">

But after deploying my app to Heroku and although I have identical settings, currency isn't shown in templates and when I open admin history I get the ValidationError like below
**TEMPLATE:**
<img width="533" alt="template - error" src="https://user-images.githubusercontent.com/56277363/80897701-f434c380-8cfb-11ea-9f15-2b4188ff4ba7.png">
**ADMIN:**
<img width="772" alt="admin - error" src="https://user-images.githubusercontent.com/56277363/80897871-a7ea8300-8cfd-11ea-95b0-07990936f2b5.png">
I've tried every workaround I could think of but nothing. 
I'm using this configuration:
```
total = MoneyField(max_digits=14, decimal_places=0, default=0, default_currency='EUR', blank=False)

CURRENCIES = ('EUR', 'GBP')
CURRENCY_CHOICES = [('EUR','EUR'), ('GBP','GBP')]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

import moneyed
from moneyed.localization import _FORMATTER, DEFAULT

_FORMATTER.add_sign_definition('DEFAULT', moneyed.EUR, suffix=' (EUR)')
_FORMATTER.add_sign_definition('DEFAULT', moneyed.GBP, suffix=' (GBP)')
```

**Comment by benjaoming** [comment]
Hi @aladinbenz 

You seem to have [monkey-patched](https://en.wikipedia.org/wiki/Monkey_patch) (no offense, it's just a term) moneyed.

This behavior depends on module load order. If `moneyed` is loaded by another module before you apply your patch, values may apply differently.

Or indeed, since this is Heroku, there is probably some concurrency going on. It should not be related to django-money.

Btw. how exactly are you printing the values in the template?

P.S. we try not to use Github issues for support questions, see: https://github.com/django-money/django-money/blob/master/.github/SUPPORT.rst

**Comment by aladinbenz** [comment]
Hi @benjaoming 

Thanks for your quick response.
I implemented moneyed following the documentation using a form widget and I'm rendering my fields as per usual.

The problem seems to happen only with history (I'm using Django simple history to track it) and only on Heroku. On the rest of the templates the currency is shown as expected. 

**The expected outcome when changing currency**  (which works locally)
<img width="561" alt="local" src="https://user-images.githubusercontent.com/56277363/80909978-ca47c500-8d2c-11ea-8b30-5fed578f8145.png">
**What really happens after deployment on Heroku** (currency showed as expected but the amount field and currency are separated, the amount is showed without currency)
<img width="507" alt="heroku" src="https://user-images.githubusercontent.com/56277363/80909996-f6fbdc80-8d2c-11ea-9b56-fcb1135ac112.png">

**Comment by benjaoming** [comment]
> I'm using Django simple history to track it

> (...)

> On the rest of the templates the currency is shown as expected.

Ah okay, it seems to be related to more than just the monkey-patch (in settings?(. It could be a broader issue with django-simple-history and custom model fields. Have you had a look at their issue tracker?

**Comment by aladinbenz** [comment]
The problem was caused by either Django or django-simple-history (or maybe both)
All I had to do is upgrade django, django-money and django-simple-history to the latest versions.

Everything is working as it should. 

Thank you for your assistance.
