### ISSUE TITLE
contrib.exchange uses deprecated urllib API

### ISSUE THREAD

**Issue by daphtdazz** [django-money/django-money#553]
[contrib.exchange.backends.base](https://github.com/django-money/django-money/blob/master/djmoney/contrib/exchange/backends/base.py#L48) calls:

```py
response = urlopen(url, cafile=certifi.where())
```

But this raises a deprecation warning:

> DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.

in recent versions of urllib.

**Comment by benjaoming** [comment]
Thanks for filing this issue @daphtdazz 

Would you be able to provide a PR with a fix to this?

**Comment by daphtdazz** [comment]
I'll try and get round to it! Might not be very soon though :-)

**Comment by benjaoming** [comment]
@daphtdazz that sounds great -- we are here to help this project move along and service contributors, feel free to ask questions :+1:

**Comment by AutumnalDream** [comment]
Would this be a correct fix? Never used urllib but have used this package.

`
def get_response(self, **params):
        url = self.get_url(**params)
        ssl_context = ssl.create_default_context()
        with urlopen(url, context=ssl_context) as f:
            response = f.read()
        return response
`
