### ISSUE TITLE
Swiss currency output is wrong.

### ISSUE THREAD

**Issue by sowinski** [django-money/django-money#558]
Hi,

the output for Swiss currency is not correct. 

Currently I get this:
`Fr.80.00`

But correct would be:
`CHF 80.00`

Or

`80.00 CHF`

How can I write a workaround for this?

**Comment by benjaoming** [comment]
Hi @sowinski - thanks for reporting this

I think this should be fixed in py-moneyed - try opening a PR changing this line:

https://github.com/limist/py-moneyed/blob/796a7ec54a5f8b0ba80085bcfb6e59e4d84a4864/moneyed/localization.py#L241
