### ISSUE TITLE
Feature request. Returning only currency with the current localization

### ISSUE THREAD

**Issue by sowinski** [django-money/django-money#559]
Hi,

it would be nice if we could return the currency in a localized form.

For example
'EUR' would be transformed to '€' 
'USD' would be transformed to '$' depending on the current local

**Comment by benjaoming** [comment]
Hi @sowinski 

This behavior should originate from py-moneyed

Maybe you can clarify to this project which part of this module that should be improved/expanded?

https://github.com/limist/py-moneyed/blob/796a7ec54a5f8b0ba80085bcfb6e59e4d84a4864/moneyed/localization.py#L379
