### ISSUE TITLE
Null=True and default_currency=None Alterfield in each makemigrations

### ISSUE THREAD

**Issue by MehdiDRI** [django-money/django-money#561]
Using null=True, default_currency=None generates a nullable currency field without issues in database (at least for sqlite db).
After generating migrations for the first time and applying them, every time we run the command python manage.py makemigrations it detects changes in model and generates a new migration file with Alterfield.

If I removed default_currency=None, no changes are detected anymore but currency field is generated as non-nullable db column with default value = DEFAULT_CURRENCY's value.

Django 3.1.1
django-money 1.1

**Comment by MehdiDRI** [comment]
Hello,
The problem has been solved when I deleted all migration files and re-makemigrations.

Regards
Mehdi

**Comment by benjaoming** [comment]
Thanks so much for getting back @MehdiDRI - I'll close the issue. Please feel free to always open up issues regardless :+1:

**Comment by eranrund** [comment]
I'm running into this exact problem with version 2.1. I cannot delete existing migrations in this project.
