### ISSUE TITLE
Incompatible with Django 3.1: import FieldDoesNotExist in django.db.models.fields was removed

### ISSUE THREAD

**Issue by stgas** [django-money/django-money#563]
The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed.
Using django-money 1.1 and Django 3.1 (min) fails as the import of FieldDoesNotExist does not work anymore.

[Django 3.1 release notes] (https://docs.djangoproject.com/en/3.1/releases/3.1/#id1)

**Comment by washeck** [comment]
Are you sure you are using django-money 1.1?

The import was fixed in https://github.com/django-money/django-money/commit/2db971c2614385838bde64ec2580f869d7b109c5

**Comment by stgas** [comment]
Oh, you are right!
It is already fixed and working - sorry i didn't check it.
