### ISSUE TITLE
Dividing not working

### ISSUE THREAD

**Issue by sowinski** [django-money/django-money#566]
Hi,

why is it only possible to use + - and * operator but not / (dividing?)

How do you devide?

Thank you

**Comment by washeck** [comment]
What do you mean? You can divide money by a number

```
In [3]: Money(2, "EUR") / 2
Out[3]: <Money: 1 EUR>
```

But dividing by money makes no sense. How much is 20 USD / 2 EUR?

**Comment by washeck** [comment]
I actually found out that the division also works but I find it strange:

```
In [5]: 2 / Money(2, "EUR")
Out[5]: <Money: 1 EUR>
```

This seems bit weird to me

**Comment by sowinski** [comment]
I refactored my code and it works now. 
I had problems using float numbers, not sure why I had a problem but it is working now.
