### ISSUE TITLE
New release with Django 3.1 support

### ISSUE THREAD

**Issue by pauloxnet** [django-money/django-money#570]
Please create a new release with official Django 3.1 support.

**Comment by Stranger6667** [comment]
Hi @pauloxnet ! Thank you for bringing this issue!

@benjaoming Hi Ben, would you have some time to make a new release?

P.S. Now I have more time to devote to `django-money`, it would be nice if @reinbach can give me publishing rights on PyPI.

**Comment by reinbach** [comment]
@Stranger6667 let me know what your pypi user is and I'll add you as a maintainer as well

**Comment by Stranger6667** [comment]
Thank you Greg! It is "Stranger6667"

**Comment by reinbach** [comment]
I should've guessed :) You should be all set

**Comment by Stranger6667** [comment]
Lovely! Thank you very much! :)

**Comment by pauloxnet** [comment]
Great. We're waiting for the new release.

**Comment by Stranger6667** [comment]
@pauloxnet 

django-money 1.2 is released :) https://pypi.org/project/django-money/1.2/

Let me know if it works as expected and feel free to reopen this issue if you'd observe any incompatibilities with Django 3.1

**Comment by pauloxnet** [comment]
@Stranger6667 thanks for the release

**Comment by Stranger6667** [comment]
You are very welcome!
