### ISSUE TITLE
removing decimals places

### ISSUE THREAD

**Issue by myaccountnameislost** [django-money/django-money#584]
how can i remove the last two decimal places?
from this ۸۵,۲۱۲,۰۰۰.۰۰ to ۸۵,۲۱۲,۰۰۰

**Comment by myaccountnameislost** [comment]
Added CURRENCY_DECIMAL_PLACES  = 0 to the settings and that solved it.

**Comment by Stranger6667** [comment]
I am glad that the issue is solved :) Feel free to open an issue if you miss something in our documentation
