### ISSUE TITLE
ValueError: Could not find manager MoneyManager in djmoney.models.managers

### ISSUE THREAD

**Issue by jamesreinhold** [django-money/django-money#590]
i am not really sure how to address this error. I have not make any changes to the Model. 
I just run a makemigrations to one of my installed apps and this is the error I get

**ValueError**: Could not find manager MoneyManager in djmoney.models.managers.
Please note that you need to inherit from managers you dynamically generated with 'from_queryset()'

**Comment by benjaoming** [comment]
Hi @jamesreinhold 

Please see this note: https://django-money.readthedocs.io/en/stable/changes.html#note-about-automatic-model-manager-patches
