### ISSUE TITLE
Creating a ArrayField(Moneyfield) only creates array of decimal like numeric[] in postgres, why? 

### ISSUE THREAD

**Issue by rajeshr188** [django-money/django-money#597]
I'm trying to create an array of moneyfield in postgres. But when saving it only saves amount as numeric with out currency code in db columns. 

My exact use case is :

From djmoney.models.fields import MoneyField

ClassTransactiontable(models.Model):
       money= MoneyField () 
Class Statementable(models.Model):
       balance = models.ArrayField(MoneyField()) ) 

In transaction table each transaction can have money of any currency
And statement table will have array of unique money instances in balance column. 

How can i achieve this? 

Is it possible to have django ArrayField with its base modelfield as MoneyField?

**Comment by Stranger6667** [comment]
Hi! I'll answer in #599
