### ISSUE TITLE
djmoney alters existing objects

### ISSUE THREAD

**Issue by moser** [django-money/django-money#603]
We have an application that uses `moneyed` and (sub-classes of) its `Money` type in a non-Django environment. We recently started integrating this into a Django app that uses djmoney and started getting weird errors in seemingly unrelated cases  because instances of `djmoney.money.Money` started showing up there.

We tracked this down to a behavior of the djmoney package in `djmoney.models.fields`:
https://github.com/django-money/django-money/blob/bb222ed619f72a0112aef8c0fd9a4823b1e6e388/djmoney/models/fields.py#L38
https://github.com/django-money/django-money/blob/bb222ed619f72a0112aef8c0fd9a4823b1e6e388/djmoney/models/fields.py#L209

The two places alter **the type of an existing object**. Can we change this to copying the objects before altering them?

**Comment by Stranger6667** [comment]
The fix is released in 1.3.1
