### ISSUE TITLE
Accept integer as acceptable value for MoneyField Model field

### ISSUE THREAD

**Issue by troygrosfield** [django-money/django-money#61]
In djmoney/models/fields.MoneyField you see the current code:
        
    class MoneyField(models.DecimalField):

        def __init__(self, verbose_name=None, name=None,
                 max_digits=None, decimal_places=None,
                 default=Money(0.0, DEFAULT_CURRENCY),
                 default_currency=DEFAULT_CURRENCY,
                 currency_choices=CURRENCY_CHOICES, **kwargs):

        if isinstance(default, basestring):
            amount, currency = default.split(" ")
            default = Money(float(amount), Currency(code=currency))
        elif isinstance(default, (float, Decimal)):
            default = Money(default, default_currency)

        if not isinstance(default, Money):
            raise Exception(
                "default value must be an instance of Money, is: %s" % str(
                    default))

What happens if I try and initialize the field with a default value of an integer, say 10?  Since an integer won't pass as a basestring, float or Decimal, this code will raise an exception.  Why not add the following:

    if isinstance(default, basestring):
        amount, currency = default.split(" ")
        default = Money(float(amount), Currency(code=currency))
    elif isinstance(default, (float, Decimal)):
        default = Money(default, default_currency)
    elif isinstance(default, int):
        default = Money(float(default), Currency(code=currency))

**Comment by benjaoming** [comment]
This works now!
