### ISSUE TITLE
why Currency is not a model?

### ISSUE THREAD

**Issue by ayushin** [django-money/django-money#616]
Would this not be logical to store all currency details (code, display_name etc) in a (localised) model?

The foreign key can be still char CURRENCY_CODE

Is there any reason it is not done this way?

**Comment by benjaoming** [comment]
In the database, there is a representation of the currency, which is not a Python class. It is then represented with instances from https://github.com/py-moneyed/py-moneyed.

django-money is designed to use py-moneyed, nothing more, nothing less.

You can see the implementation here - it is a class.

https://github.com/py-moneyed/py-moneyed/blob/master/src/moneyed/classes.py#L20
