### ISSUE TITLE
Support py-moneyed 2.0

### ISSUE THREAD

**Issue by antonagestam** [django-money/django-money#621]
While py-moneyed 2.0 hasn't been released yet, I thought it was worth keeping an issue open with the plan laid out in #567, copying it in here:

#### In version 2.0 [done]

- The py-moneyed dependency is pinned to `>1,<2`.
- Setting and reading `decimal_places_display` starts giving a deprecation warning.
- Setting `CURRENCY_DECIMAL_PLACES_DISPLAY` in settings starts giving a
  deprecation warning.
- `CURRENCY_DECIMAL_PLACES_DISPLAY` and `Money.decimal_places_display`
  both being unset results in `Money.__str__` using the new `l10n.format_money()`.
- Settings and properties for `format` and `currency_digits` are introduced,
  similar to how `decimal_places_display` currently works.

#### In version 3.0

- The py-moneyed dependency is pinned to `>2`.
- Calling the old `localization.format_money()` is removed, we are now always
  calling the new `l10n.format_money()`.
- The `decimal_places_display` property is removed.
- The `CURRENCY_DECIMAL_PLACES_DISPLAY` setting is removed.

**Comment by Stranger6667** [comment]
`py-moneyed==2.0` is released :tada:

**Comment by SchrodingersGat** [comment]
Note that unless you specify a particular version of py-moneyed (e.g. in requirements.txt) then django-money will now break:

![image](https://user-images.githubusercontent.com/10080325/119759681-0297e380-beec-11eb-93d4-f05aec78241c.png)

**Comment by antonagestam** [comment]
@SchrodingersGat That should only be true if py-moneyed is a first-hand dependency. django-money's py-moneyed dependency is already pinned to <2.

**Comment by SchrodingersGat** [comment]
My project is pinned to v1.1 which requires py-moneyed >=0.8

(I realize that 1.1 is a very old release now!)

**Comment by antonagestam** [comment]
@SchrodingersGat Ah OK, then yes you'll have to pin it. Note that that is usually how Python dependencies are specified in packages, e.g. no upper bounds. See for instance [Django's dependencies](https://github.com/django/django/blob/main/setup.cfg#L39).e

Also note that it's best practice for applications to use a tool like pip-tools to pin all project dependencies to specific versions, not just first-hand dependencies.

**Comment by antonagestam** [comment]
Just an FYI. Before working on this ticket I intend to first:

- Work on dropping support for legacy versions of Django and Python https://github.com/django-money/django-money/pull/612.
- Adding support for Django 3.2 (hopefully just an addition to the test suite, there shouldn't be dramatic changes needed).

**Comment by flaeppe** [comment]
Can this be closed through #638?

**Comment by antonagestam** [comment]
@flaeppe Yes! 🥳
