### ISSUE TITLE
CURRENCY_DECIMAL_PLACES_DISPLAY tested wrong...

### ISSUE THREAD

**Issue by nerdoc** [django-money/django-money#624]
in #621  you say that using CURRENCY_DECIMAL_PLACES_DISPLAY produces a deprecation warning. But the code for that is wrong IMHO:
https://github.com/django-money/django-money/blob/b2acda356893c590f6446b507699a801f7e1ea72/djmoney/settings.py#L29

you try to get the value, and if it is `None`you print a deprecation warning... But if its not defined, you weill get None.
In my project there is no `CURRENCY_DECIMAL_PLACES_DISPLAY`defined in settings, and I get this deprecation warning.

**Comment by nerdoc** [comment]
I created a sinle-shot PR - please have a look.

**Comment by Stranger6667** [comment]
Well-spotted! Thank you for reporting & fixing it :) I'll release the fix during the day

**Comment by Stranger6667** [comment]
Released in `2.0.1`
