### ISSUE TITLE
__get_current_locale  does not return the locale but the language code

### ISSUE THREAD

**Issue by YAmikep** [django-money/django-money#63]
Hi,

I had a problem to use the formatting made for the locale "en_US". Note the "_" instead of a "-"
The locale is defined on py-moneyed:
https://github.com/limist/py-moneyed/blob/9ee56146ce67872f12509c2eb62da59701c51f0a/src/moneyed/localization.py#L326

However, in the __get_current_locale method, you use

```
locale = translation.get_language()
```

which actually returns the language code (with the "-").
Then py-moneyed cannot find the given locale "en-us" in its configuration and uses the default one for USD.

There is a method in django translations utils to return a locale code based on the language code: 
https://github.com/django/django/blob/master/django/utils/translation/trans_real.py#L71

Maybe you could use it to really get a locale to pass to the formatter ?

Thanks

**Comment by Stranger6667** [comment]
The issue was fixed in 9cf4e991b4fac30fe99f3207ac48c96f06304550
