### ISSUE TITLE
Migration created after makemigrations with DEFAULT_AUTO_FIELD modified settings

### ISSUE THREAD

**Issue by ventur40** [django-money/django-money#684]
An migration called "0002_alter_rate_id.py" created after running "makemigrations" with
`DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'`

**Comment by benjaoming** [comment]
Thanks for the report! Can you describe how you would propose to solve this?

**Comment by ventur40** [comment]
I have done a temporal workaround with a new app config:
```
class ModifiedDjmoneyContribExchangeConfig(AppConfig):
       name = 'djmoney.contrib.exchange'
       default_auto_field = 'django.db.models.AutoField'

```

And replacing the installed_apps line
> 
        INSTALLED_APPS = [
        ...
        # replace with 'djmoney.contrib.exchange',
        '<path_to_file>.apps.ModifiedDjmoneyContribExchangeConfig',
        ]

**Comment by benjaoming** [comment]
I see now! I wondered what the issue was since djmoney does specify its default_auto_field.

There's an App Config missing here:

https://github.com/django-money/django-money/tree/main/djmoney/contrib/exchange

PR is welcome :+1: 

Btw. do you need `BigAutoField` because of the models in `djmoney.contrib.exchange`?

**Comment by ventur40** [comment]
PR created.

I don't need `BigAutoField`, it is just a test project.

**Comment by ventur40** [comment]
My workaround is not working because of:
```
    if "djmoney.contrib.exchange" not in settings.INSTALLED_APPS:
        raise ImproperlyConfigured(
            "You have to add 'djmoney.contrib.exchange' to INSTALLED_APPS in order to use currency exchange"
        )
```
inside `convert_money` function.

Any idea on how to fix this?

**Comment by benjaoming** [comment]
Good that you found that! Perhaps the expression can be rewritten? `if not any(app.startswith("djmoney.contrib.exchange") for app in settings.INSTALLED_APPS)`

**Comment by alexnorgaard** [comment]
Any news on this? What did you end up with as a workaround? I see the CI checks for the PR were cancelled

**Comment by alexnorgaard** [comment]
I have made a fix with a different approach here: https://github.com/django-money/django-money/pull/716 
The change explicitly sets the id field for the `Rate` model, circumventing the global setting for `DEFAULT_AUTO_FIELD`

**Comment by alexnorgaard** [comment]
This issue should probably be closed

**Comment by benjaoming** [comment]
Thanks for confirming :pray:
