### ISSUE TITLE
ModuleNotFoundError: No module named 'django.forms.util'

### ISSUE THREAD

**Issue by shaheem-pp** [django-money/django-money#690]
I have a model class for Student 

```
class Student(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, primary_key = True)
    fee = MoneyField(max_digits=14,
                             decimal_places=2,
                             default_currency='INR',
                             null = True, blank = True)
```
I used the MoneyField for fee field, but I got error

<img width="1440" alt="Screenshot 2022-09-30 at 5 01 02 PM" src="https://user-images.githubusercontent.com/46243023/193263119-e02409f0-107a-4048-ae47-9b79b41af0df.png">

So what is the issue?

I'm using Django==4.1.1

**Comment by benjaoming** [comment]
You should ask the django-moneyfield project that question :wink: 

https://pypi.org/project/django-moneyfield/
