### ISSUE TITLE
Updating model generates error on migration

### ISSUE THREAD

**Issue by alexandremjacques** [django-money/django-money#693]
I'm trying to add a new field to my model:

```
 rental_total_amount = MoneyField(max_digits=12, decimal_places=2, default_amount=0)
```

But, when I run the migration command, and because this field is required, I'm prompted to populate with a default value (that can be 0). If I insert 0 as a reponse to the command prompt, I get:

```
AttributeError: 'int' object has no attribute 'amount'
```

Any way to initialize this field on migrations?

TIA

**Comment by benjaoming** [comment]
Hi! I think you should set `default=Money(...)` and then you will have a clearly defined set of amount+currency.

**Comment by alexandremjacques** [comment]
Hi!

It worked. Thanks!
