### ISSUE TITLE
3.1 release not found on PyPi

### ISSUE THREAD

**Issue by jacobmaster** [django-money/django-money#705]
3.1.0 version of package is not showing for the project. 
https://pypi.org/project/django-money/ - the version shown is 3.0.0.
Are there any problems with publishing the package version?

**Comment by benjaoming** [comment]
There might be! The release process has been moved to a GitHub Action. @Stranger6667 seems like the release didn't make it to https://pypi.org/project/django-money/

The GitHub automation seems to be out to lunch.

![image](https://user-images.githubusercontent.com/374612/233861436-bad84be5-1874-418f-ae52-aaed0e4263ab.png)

**Comment by benjaoming** [comment]
I guess the idea of "unattended" sort of dies when the unattended system isn't really built to be unattended :) But okay, we've made the decision to benefit from GitHub actions, and let's do that :100: Seems we need to just check up on releases after they've been triggered.

**Comment by Stranger6667** [comment]
It seems like `ubuntu-18.04` [was deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) some time ago :( I missed that they deprecated this and thought that it was some kind of a temporary issue. Will take a look at it now, sorry for the trouble

**Comment by benjaoming** [comment]
@Stranger6667 I don't think you have to be sorry about this :) The lack of a timeout here is appalling :)

**Comment by benjaoming** [comment]
Thanks for telling us that it was missing @jacobmaster :heart:
