### ISSUE TITLE
py-moneyed version

### ISSUE THREAD

**Issue by dmwyatt** [django-money/django-money#71]
The readme states: 
>3.2.x*, 3.3.x* (* These versions of Python work only for the moment when you install the following fork "py-moneyed" https://github.com/fizista/py-moneyed/tree/python3 )

Is this still the case?  The upstream version of py-moneyed states in its readme:
>The py-moneyed package has been tested with Python 2.6, 2.7, 3.2, 3.3 and PyPy 2.1.

And, according to the commit history, that comment about the upstream (limist's) supporting Python 3.x comes from a commit authored by the author of the version you recommend in your readme, so I'm wondering if the applicable fixes from fizista's version were merged into limist's version.

**Comment by benjaoming** [comment]
We support it all! The tox.ini file is the best source to have it verified.
