### ISSUE TITLE
Update ARS rate please!

### ISSUE THREAD

**Issue by sirDemian** [django-money/django-money#723]
Hi there
The argentinian government has devaluaed its currency at 20%.
When can we expect to have this updated?
Thanks
Demian

**Comment by benjaoming** [comment]
Sorry that happened :/

I think you should be referring to the currency backend that's in use. django-money doesn't have anything to do with currency rates, see:

https://github.com/django-money/django-money#working-with-exchange-rates

**Comment by sirDemian** [comment]
Thanks @benjaoming, I saw this link after send issue.
