### ISSUE TITLE
CELERYBEAT_SCHEDULE not being picked up

### ISSUE THREAD

**Issue by foarsitter** [django-money/django-money#760]
Thans for providing this library, really like how easy everything is to work with. 

The example for using a periodic task with celery beat is really helpful to get thing going. 

One minor concern for me was that  `CELERYBEAT_SCHEDULE` isn't picked up *. 

The name of the variable new style is `beat_schedule`, so using config_from_object with namespace='CELERY' doesn't pick up `CELERYBEAT_SCHEDULE` but naming it `CELERY_BEAT_SCHEDULE` does. 

* https://docs.celeryq.dev/en/latest/userguide/configuration.html#beat-schedule

**Comment by benjaoming** [comment]
Thanks for quickly fixing this @foarsitter :clap: 

Fixed in https://github.com/django-money/django-money/pull/761
