### ISSUE TITLE
Hidding Currency From the admin panel 

### ISSUE THREAD

**Issue by omargawdat** [django-money/django-money#770]
I find it difficult to hide the currency to auto-set it in the admin panel so is there an easy way to do this task as it's supposed to be easy?   

<img width="707" alt="image" src="https://github.com/django-money/django-money/assets/53629777/10d8444d-8f07-4205-9a7a-313e7080b715">

**Comment by benjaoming** [comment]
This sounds like a UX task.

Could you say under which conditions that you would hide/show the currency?

Possibly, this discussion is also related: https://github.com/django-money/django-money/discussions/765

**Comment by omargawdat** [comment]
First thanks for the great work!! 
I have two scenarios, 
first when the form include many prices and I want to display only the prices and the currency on the top for making it user friendly 

Second is when I need to automatically set the price based on some informations like user country so I don't want to overwhelm admin to pick the currency as it will be auto calculated and I even can't make the price changeable while making currency disable or hidden

**Comment by benjaoming** [comment]
> first when the form include many prices and I want to display only the prices and the currency on the top for making it user friendly

I think you might solve this with your own custom CSS and JS ([example](https://gist.github.com/rg3915/26076942ef4b0564cfa4b398a92c9b51))

What you may be able to do with relatively little code is to:

1) Hide all currency fields except the first one (CSS)
2) When changing the visible currency field, the others should also change (JS)
3) You may want to show the other fields when then change?
4) You may want to raise an error in the Model's `.clean()` if the currencies aren't all the same.

> Second is when I need to automatically set the price based on some informations like user country so I don't want to overwhelm admin to pick the currency as it will be auto calculated and I even can't make the price changeable while making currency disable or hidden

This sounds like a strong argument to consider the field either invisible to the user or readonly: https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.readonly_fields

**Comment by benjaoming** [comment]
So, did you solve it?

**Comment by omargawdat** [comment]
> So, did you solve it?

actually yes I solved it, your answer helped me a lot and I appreciate it, thanks man !!
