### ISSUE TITLE
Add __version__ attribute

### ISSUE THREAD

**Issue by arthurk** [django-money/django-money#89]
It would be nice to add a `__version__` attribute (as specified in http://legacy.python.org/dev/peps/pep-0396/) to the djmoney module, so it's possible to check which version is installed.

Thanks!

**Comment by benjaoming** [comment]
Sad news.

I would love to do it, but currently `djmoney/__init__.py` imports django, so we would have to set the version too many places.

Once we have fixed the `__init__.py` file to stop importing and monkey patching over in #127 we could add this.
