### ISSUE TITLE
MoneyField currency_choices confusion

### ISSUE THREAD

**Issue by spookylukey** [django-money/django-money#97]
Current MoneyField `__init__` accepts both `choices` and `currency_choices` keyword args.

`choices`, however is completely ignored (not withstanding a line that assigns to it - the value is never used).

On the other hand `currency_choices` is used (it is passed to the `ChoiceField`, but if you use it, you get a warning saying that it is deprecated!

It's not obvious to me what the intended behaviour should be. Either it should issue the warning for `choices` not `currency_choices`, or it should actually use `choices`.

**Comment by benjaoming** [comment]
I'm pretty sure this is gone now.

Using the `choices` kwarg should not have an effect since it's always overwritten in the `contribute_to_class` method.

**Comment by benjaoming** [comment]
Nope, still there:

```python
        if currency_choices != CURRENCY_CHOICES:
            warn('currency_choices will be deprecated in favor of choices', PendingDeprecationWarning)
            choices = currency_choices
```

**Comment by benjaoming** [comment]
Now it works
