### ISSUE TITLE
Magic money querying ability does not chain

### ISSUE THREAD

**Issue by spookylukey** [django-money/django-money#99]
Take, for example, `VanillaMoneyFieldTestCase.testCurrencySearch`. In the line

    shouldBeEmpty = ModelWithVanillaMoneyField.objects.filter(money__lt=otherMoney)

if you replace `objects` with `objects.all().all()`, then the test fails.

Basically, you end up with a vanilla `QuerySet` that does not 'understand money'. However, there is no warning - the query appears to succeed, but returns the wrong answer. This hugely violates expectations - people normally chain ORM methods a lot, and don't expect them to suddenly behave differently because of an earlier `filter` or `order_by` etc.

This is a serious flaw in this feature, IMO. If it can't be fixed, I'd recommend pulling it completely. The alternative method (explicit filtering against the `_currency` field) will always work.

To solve it, I think you need a custom `QuerySet` subclass. It is this that should have `understands_money` applied. And you then need to do patching that will return this `QuerySet` rather than anything else. I may be able to work something up for this.

**Comment by Stranger6667** [comment]
@benjaoming , I think it is not relevant anymore - chaining works fine.

**Comment by benjaoming** [comment]
Closing :)
